#!/usr/bin/env python3
"""Emit the independent exact golden mission summary for the Phase 1 core."""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path

from emit_force_bindings import (
    divide_scaled,
    halve_nonnegative,
    interpolate,
    multiply_scaled,
    scenario_values,
)


FNV_OFFSET = 2_166_136_261
FNV_PRIME = 16_777_619


def hash_word(checksum: int, word: int) -> int:
    unsigned = word & 0xFFFF_FFFF
    for shift in range(0, 32, 8):
        checksum ^= (unsigned >> shift) & 0xFF
        checksum = (checksum * FNV_PRIME) & 0xFFFF_FFFF
    return checksum


def hash_state(checksum: int, state: dict[str, int]) -> int:
    for field in ("step", "time", "altitude", "velocity", "acceleration", "mass", "propellant"):
        checksum = hash_word(checksum, state[field])
    return checksum


def build_summary() -> dict[str, int]:
    root = Path(__file__).resolve().parents[2]
    scenario = scenario_values(root)
    vectors = json.loads(
        (root / "phase0" / "vectors" / "phase0-v1.json").read_text(encoding="utf-8")
    )
    environment = vectors["environment"]
    altitudes = environment["altitude_knots_q12"]
    densities = environment["density_q28"]
    gravities = environment["gravity_q28"]
    state = {
        "step": 0,
        "time": 0,
        "altitude": scenario["initial_altitude"],
        "velocity": scenario["initial_velocity"],
        "acceleration": 0,
        "mass": scenario["initial_mass"],
        "propellant": scenario["initial_propellant"],
    }
    initial_truth_checksum = hash_state(FNV_OFFSET, state)
    checksum = FNV_OFFSET
    cutoff_events = 0

    while state["step"] < scenario["steps"]:
        density = interpolate(state["altitude"], altitudes, densities)
        gravity = interpolate(state["altitude"], altitudes, gravities)
        engine_active = (
            state["propellant"] > 0 and state["time"] < scenario["burn_duration"]
        )
        speed_squared = multiply_scaled(abs(state["velocity"]), abs(state["velocity"]), 28)
        density_speed_squared = multiply_scaled(density, speed_squared, 28)
        twice_drag = multiply_scaled(density_speed_squared, scenario["cda"], 24)
        drag_magnitude = halve_nonnegative(twice_drag)
        drag = (
            -drag_magnitude
            if state["velocity"] > 0
            else drag_magnitude if state["velocity"] < 0 else 0
        )
        weight = multiply_scaled(state["mass"], gravity, 28)
        thrust = scenario["thrust"] if engine_active else 0
        net_force = thrust - weight + drag
        acceleration = divide_scaled(net_force, state["mass"], 28)
        if abs(net_force) > 2_048_000 or abs(acceleration) > 26_843_546:
            raise ValueError(f"golden mission force envelope escaped at step {state['step']}")

        velocity = state["velocity"] + multiply_scaled(
            acceleration, scenario["timestep"], 20
        )
        altitude = state["altitude"] + multiply_scaled(
            velocity, scenario["timestep"], 28
        )
        time = state["time"] + scenario["timestep"]
        requested = (
            multiply_scaled(scenario["mass_flow"], scenario["timestep"], 20)
            if engine_active
            else 0
        )
        consumed = min(requested, state["propellant"])
        propellant = state["propellant"] - consumed
        mass = state["mass"] - consumed
        if not -8_192 <= altitude <= 8_192_000:
            raise ValueError(f"golden mission altitude envelope escaped at step {state['step']}")
        if not -134_217_728 <= velocity <= 134_217_728:
            raise ValueError(f"golden mission velocity envelope escaped at step {state['step']}")
        if mass < scenario["dry_mass"] or not 0 <= propellant <= mass:
            raise ValueError(f"golden mission mass invariant failed at step {state['step']}")
        engine_cutoff = engine_active and (
            propellant == 0 or time >= scenario["burn_duration"]
        )
        state = {
            "step": state["step"] + 1,
            "time": time,
            "altitude": altitude,
            "velocity": velocity,
            "acceleration": acceleration,
            "mass": mass,
            "propellant": propellant,
        }
        cutoff_events += 1 if engine_cutoff else 0
        checksum = hash_state(checksum, state)

    return {
        **state,
        "initial_truth_checksum": initial_truth_checksum,
        "checksum": checksum,
        "cutoff_events": cutoff_events,
    }


def build_source() -> str:
    summary = build_summary()
    return "\n".join(
        [
            "// Generated by phase1/reference/emit_mission_bindings.py.",
            "// Do not edit by hand.",
            "",
            f'pub const INITIAL_TRUTH_CHECKSUM: u32 = 0x{summary["initial_truth_checksum"]:08x};',
            f'pub const FINAL_STEP: u32 = {summary["step"]};',
            f'pub const FINAL_TIME_Q16: i32 = {summary["time"]};',
            f'pub const FINAL_ALTITUDE_Q12: i32 = {summary["altitude"]};',
            f'pub const FINAL_VELOCITY_Q24: i32 = {summary["velocity"]};',
            f'pub const FINAL_ACCELERATION_Q28: i32 = {summary["acceleration"]};',
            f'pub const FINAL_MASS_Q12: i32 = {summary["mass"]};',
            f'pub const FINAL_PROPELLANT_Q12: i32 = {summary["propellant"]};',
            f'pub const FINAL_CHECKSUM: u32 = 0x{summary["checksum"]:08x};',
            f'pub const CUTOFF_EVENTS: u16 = {summary["cutoff_events"]};',
            "",
        ]
    )


def output_paths() -> tuple[Path, Path]:
    root = Path(__file__).resolve().parents[2]
    source = root / "phase1" / "generated" / "mission_v1.rs"
    digest = root / "phase1" / "generated" / "mission_v1.rs.sha256"
    return source, digest


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail when generated summary is stale")
    parser.add_argument("--stdout", action="store_true", help="write generated Rust to stdout")
    arguments = parser.parse_args()
    payload = build_source().encode("utf-8")
    digest = hashlib.sha256(payload).hexdigest()
    source_path, digest_path = output_paths()
    digest_payload = f"{digest}  {source_path.name}\n".encode("ascii")
    if arguments.stdout:
        sys.stdout.buffer.write(payload)
        return 0
    if arguments.check:
        stale = []
        if not source_path.exists() or source_path.read_bytes() != payload:
            stale.append(source_path)
        if not digest_path.exists() or digest_path.read_bytes() != digest_payload:
            stale.append(digest_path)
        if stale:
            print("Phase 1 mission bindings are stale or missing:", file=sys.stderr)
            for path in stale:
                print(f"  {path}", file=sys.stderr)
            return 1
        print(f"Phase 1 mission bindings are current: {digest}")
        return 0
    source_path.parent.mkdir(parents=True, exist_ok=True)
    source_path.write_bytes(payload)
    digest_path.write_bytes(digest_payload)
    print(f"Wrote {source_path}")
    print(f"Wrote {digest_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
