#!/usr/bin/env python3
"""Emit the accepted Phase 1 environment tables as production Rust data."""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path


ENVIRONMENT_NAME = "earth.simple-atmosphere.v1"


def fnv1a(text: str) -> int:
    value = 2_166_136_261
    for byte in text.encode("utf-8"):
        value ^= byte
        value = (value * 16_777_619) & 0xFFFF_FFFF
    return value


def rust_i32_array(name: str, values: list[int]) -> list[str]:
    lines = [f"pub const {name}: [i32; {len(values)}] = ["]
    row: list[str] = []
    for value in values:
        row.append(str(value))
        if len(row) == 6:
            lines.append("    " + ", ".join(row) + ",")
            row = []
    if row:
        lines.append("    " + ", ".join(row) + ",")
    lines.append("];")
    return lines


def build_source() -> str:
    root = Path(__file__).resolve().parents[2]
    vectors = json.loads(
        (root / "phase0" / "vectors" / "phase0-v1.json").read_text(encoding="utf-8")
    )
    numeric = json.loads(
        (root / "phase0" / "numeric" / "numeric-v1.json").read_text(encoding="utf-8")
    )
    environment = vectors["environment"]
    formats = numeric["formats"]
    if formats["altitude"]["fractional_bits"] != 12:
        raise ValueError("production altitude format is no longer Q20.12")
    if formats["density"]["fractional_bits"] != 28:
        raise ValueError("production density format is no longer Q4.28")
    if formats["acceleration"]["fractional_bits"] != 28:
        raise ValueError("production gravity format is no longer Q4.28")

    altitudes = environment["altitude_knots_q12"]
    densities = environment["density_q28"]
    gravities = environment["gravity_q28"]
    if not altitudes or len(altitudes) != len(densities) or len(altitudes) != len(gravities):
        raise ValueError("environment tables must be non-empty and equally sized")
    if any(right <= left for left, right in zip(altitudes, altitudes[1:])):
        raise ValueError("environment altitude knots must be strictly increasing")
    if any(value < 0 for value in densities) or any(value <= 0 for value in gravities):
        raise ValueError("environment values escape their physical domain")

    lines = [
        "// Generated by phase1/reference/emit_environment_bindings.py.",
        "// Do not edit by hand.",
        "",
        f'pub const ENVIRONMENT_NAME: &str = "{ENVIRONMENT_NAME}";',
        f"pub const ENVIRONMENT_ID: u32 = 0x{fnv1a(ENVIRONMENT_NAME):08x};",
        f"pub const TABLE_LENGTH: usize = {len(altitudes)};",
        "",
    ]
    lines.extend(rust_i32_array("ALTITUDE_KNOTS_Q12", altitudes))
    lines.append("")
    lines.extend(rust_i32_array("DENSITY_Q28", densities))
    lines.append("")
    lines.extend(rust_i32_array("GRAVITY_Q28", gravities))
    lines.append("")
    return "\n".join(lines)


def output_paths() -> tuple[Path, Path]:
    root = Path(__file__).resolve().parents[2]
    source = root / "phase1" / "generated" / "environment_v1.rs"
    digest = root / "phase1" / "generated" / "environment_v1.rs.sha256"
    return source, digest


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail when generated bindings are stale")
    parser.add_argument("--stdout", action="store_true", help="write generated Rust to stdout")
    arguments = parser.parse_args()
    payload = build_source().encode("utf-8")
    digest = hashlib.sha256(payload).hexdigest()
    source_path, digest_path = output_paths()
    digest_payload = f"{digest}  {source_path.name}\n".encode("ascii")
    if arguments.stdout:
        sys.stdout.buffer.write(payload)
        return 0
    if arguments.check:
        stale = []
        if not source_path.exists() or source_path.read_bytes() != payload:
            stale.append(source_path)
        if not digest_path.exists() or digest_path.read_bytes() != digest_payload:
            stale.append(digest_path)
        if stale:
            print("Phase 1 environment bindings are stale or missing:", file=sys.stderr)
            for path in stale:
                print(f"  {path}", file=sys.stderr)
            return 1
        print(f"Phase 1 environment bindings are current: {digest}")
        return 0
    source_path.parent.mkdir(parents=True, exist_ok=True)
    source_path.write_bytes(payload)
    digest_path.write_bytes(digest_payload)
    print(f"Wrote {source_path}")
    print(f"Wrote {digest_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
