#!/usr/bin/env python3
"""Emit the production numeric self-test pack from accepted Phase 0 artifacts."""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from decimal import Decimal, ROUND_HALF_UP
from pathlib import Path
from typing import Any


def raw(value: str, fractional_bits: int) -> int:
    return int((Decimal(value) * (1 << fractional_bits)).to_integral_value(rounding=ROUND_HALF_UP))


def rust_array(name: str, type_name: str, rows: list[str]) -> list[str]:
    output = [f"pub const {name}: &[{type_name}] = &["]
    output.extend(f"    {row}," for row in rows)
    output.append("];")
    return output


def checkpoint_rows(checkpoints: list[dict[str, Any]], kind: str) -> list[str]:
    if kind == "motion":
        return [
            "MotionCheckpoint { "
            f"step: {item['step']}, altitude_q12: {item['altitude_q12']}, "
            f"velocity_q24: {item['velocity_q24']} "
            "}"
            for item in checkpoints
        ]
    return [
        "MassCheckpoint { "
        f"step: {item['step']}, mass_q12: {item['mass_q12']}, "
        f"propellant_q12: {item['propellant_q12']} "
        "}"
        for item in checkpoints
    ]


def acceleration_cases(analytic: dict[str, Any]) -> tuple[list[str], list[str]]:
    source = [
        *analytic["semi_implicit_convergence"],
        analytic["negative_acceleration"],
    ]
    seen: set[tuple[str, str]] = set()
    definitions: list[str] = []
    cases: list[str] = []
    case_number = 0
    for item in source:
        key = (item["timestep_s"], item["acceleration_km_s2"])
        if key in seen:
            continue
        seen.add(key)
        case_number += 1
        checkpoint_name = f"ACCELERATION_CHECKPOINTS_{case_number}"
        definitions.extend(rust_array(checkpoint_name, "MotionCheckpoint", checkpoint_rows(item["checkpoints"], "motion")))
        definitions.append("")
        cases.append(
            "AccelerationCase { "
            f"timestep_q16: {raw(item['timestep_s'], 16)}, "
            f"acceleration_q28: {raw(item['acceleration_km_s2'], 28)}, "
            f"steps: {item['steps']}, checkpoints: {checkpoint_name} "
            "}"
        )
    return definitions, cases


def build_source() -> str:
    root = Path(__file__).resolve().parents[2]
    phase0 = json.loads((root / "phase0" / "vectors" / "phase0-v1.json").read_text(encoding="utf-8"))
    numeric = json.loads((root / "phase0" / "numeric" / "numeric-v1.json").read_text(encoding="utf-8"))
    scenario = json.loads((root / "phase0" / "numeric" / "examples" / "phase1-vertical.json").read_text(encoding="utf-8"))
    arithmetic = phase0["arithmetic"]
    analytic = numeric["analytic_cases"]

    lines = [
        "// Generated by phase1/reference/emit_numeric_bindings.py.",
        "// Do not edit by hand.",
        "",
        f'pub const NUMERIC_CONTRACT: &str = "{numeric["contract"]}";',
        "",
        "#[derive(Clone, Copy)]",
        "pub struct MultiplyVector {",
        "    pub a: i32,",
        "    pub b: i32,",
        "    pub shift: u8,",
        "    pub expected: i32,",
        "    pub expected_faults: u8,",
        "}",
        "",
        "#[derive(Clone, Copy)]",
        "pub struct DivideVector {",
        "    pub numerator: i32,",
        "    pub denominator: i32,",
        "    pub shift: u8,",
        "    pub expected: i32,",
        "    pub expected_faults: u8,",
        "}",
        "",
        "#[derive(Clone, Copy)]",
        "pub struct InterpolationVector {",
        "    pub altitude_q12: i32,",
        "    pub density_q28: i32,",
        "    pub gravity_q28: i32,",
        "}",
        "",
        "#[derive(Clone, Copy)]",
        "pub struct MotionCheckpoint {",
        "    pub step: u32,",
        "    pub altitude_q12: i32,",
        "    pub velocity_q24: i32,",
        "}",
        "",
        "#[derive(Clone, Copy)]",
        "pub struct MassCheckpoint {",
        "    pub step: u32,",
        "    pub mass_q12: i32,",
        "    pub propellant_q12: i32,",
        "}",
        "",
        "#[derive(Clone, Copy)]",
        "pub struct AccelerationCase {",
        "    pub timestep_q16: i32,",
        "    pub acceleration_q28: i32,",
        "    pub steps: u32,",
        "    pub checkpoints: &'static [MotionCheckpoint],",
        "}",
        "",
    ]

    multiply_rows = [
        "MultiplyVector { "
        f"a: {item['a']}, b: {item['b']}, shift: {item['shift']}, "
        f"expected: {item['expected']}, expected_faults: {1 if item['name'].startswith('saturate_') else 0} "
        "}"
        for item in arithmetic["multiply_scaled"]
    ]
    lines.extend(rust_array("MULTIPLY_VECTORS", "MultiplyVector", multiply_rows))
    lines.append("")

    divide_rows = [
        "DivideVector { "
        f"numerator: {item['numerator']}, denominator: {item['denominator']}, "
        f"shift: {item['shift']}, expected: {item['expected']}, "
        f"expected_faults: {1 if item['name'].startswith('saturate_') else 0} "
        "}"
        for item in arithmetic["divide_scaled"]
    ]
    lines.extend(rust_array("DIVIDE_VECTORS", "DivideVector", divide_rows))
    lines.append("")

    interpolation_rows = [
        "InterpolationVector { "
        f"altitude_q12: {item['altitude_q12']}, density_q28: {item['density_q28']}, "
        f"gravity_q28: {item['gravity_q28']} "
        "}"
        for item in arithmetic["interpolation"]
    ]
    lines.extend(rust_array("INTERPOLATION_VECTORS", "InterpolationVector", interpolation_rows))
    lines.append("")

    constant_velocity = analytic["constant_velocity"]
    lines.append(f"pub const CONSTANT_VELOCITY_TIMESTEP_Q16: i32 = {raw(constant_velocity['timestep_s'], 16)};")
    lines.append(f"pub const CONSTANT_VELOCITY_STEPS: u32 = {constant_velocity['steps']};")
    lines.extend(rust_array("CONSTANT_VELOCITY_CHECKPOINTS", "MotionCheckpoint", checkpoint_rows(constant_velocity["checkpoints"], "motion")))
    lines.append("")

    definitions, cases = acceleration_cases(analytic)
    lines.extend(definitions)
    lines.extend(rust_array("ACCELERATION_CASES", "AccelerationCase", cases))
    lines.append("")

    mass_case = analytic["constant_mass_flow"]
    lines.append(f"pub const MASS_FLOW_TIMESTEP_Q16: i32 = {raw(mass_case['timestep_s'], 16)};")
    lines.append(f"pub const MASS_FLOW_Q16: i32 = {raw(scenario['vehicle']['mass_flow_t_s'], 16)};")
    lines.append(f"pub const DRY_MASS_Q12: i32 = {raw(scenario['vehicle']['dry_mass_t'], 12)};")
    lines.append(f"pub const MASS_FLOW_STEPS: u32 = {mass_case['steps']};")
    lines.extend(rust_array("MASS_FLOW_CHECKPOINTS", "MassCheckpoint", checkpoint_rows(mass_case["checkpoints"], "mass")))
    lines.append("")
    return "\n".join(lines)


def output_paths() -> tuple[Path, Path]:
    root = Path(__file__).resolve().parents[2]
    source = root / "phase1" / "generated" / "numeric_v1.rs"
    digest = root / "phase1" / "generated" / "numeric_v1.rs.sha256"
    return source, digest


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail when generated bindings are stale")
    parser.add_argument("--stdout", action="store_true", help="write generated Rust to stdout")
    arguments = parser.parse_args()
    payload = build_source().encode("utf-8")
    digest = hashlib.sha256(payload).hexdigest()
    source_path, digest_path = output_paths()
    digest_payload = f"{digest}  {source_path.name}\n".encode("ascii")
    if arguments.stdout:
        sys.stdout.buffer.write(payload)
        return 0
    if arguments.check:
        stale = []
        if not source_path.exists() or source_path.read_bytes() != payload:
            stale.append(source_path)
        if not digest_path.exists() or digest_path.read_bytes() != digest_payload:
            stale.append(digest_path)
        if stale:
            print("Phase 1 numeric bindings are stale or missing:", file=sys.stderr)
            for path in stale:
                print(f"  {path}", file=sys.stderr)
            return 1
        print(f"Phase 1 numeric bindings are current: {digest}")
        return 0
    source_path.parent.mkdir(parents=True, exist_ok=True)
    source_path.write_bytes(payload)
    digest_path.write_bytes(digest_payload)
    print(f"Wrote {source_path}")
    print(f"Wrote {digest_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
