#!/usr/bin/env python3
"""Emit deterministic Rust and C++ bindings for Phase 0 vectors."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any


PROJECT_ROOT = Path(__file__).resolve().parents[2]
INPUT_PATH = PROJECT_ROOT / "phase0" / "vectors" / "phase0-v1.json"
RUST_PATH = PROJECT_ROOT / "phase0" / "generated" / "phase0_vectors.rs"
CPP_PATH = PROJECT_ROOT / "phase0" / "generated" / "phase0_vectors.hpp"


def load_document() -> dict[str, Any]:
    return json.loads(INPUT_PATH.read_text(encoding="utf-8"))


def rust_i32(value: int) -> str:
    if value == -(1 << 31):
        return "i32::MIN"
    if value == (1 << 31) - 1:
        return "i32::MAX"
    return str(value)


def cpp_long(value: int) -> str:
    if value == -(1 << 31):
        return "KSA64_I32_MIN"
    if value == (1 << 31) - 1:
        return "KSA64_I32_MAX"
    return f"{value}L"


def emit_rust(document: dict[str, Any]) -> str:
    arithmetic = document["arithmetic"]
    environment = document["environment"]
    lines = [
        "// Generated by phase0/reference/emit_candidate_vectors.py.",
        "// Do not edit by hand.",
        "",
        "#[repr(C)]",
        "#[derive(Clone, Copy, Debug)]",
        "pub struct MultiplyVector {",
        "    pub a: i32,",
        "    pub b: i32,",
        "    pub shift: u8,",
        "    pub expected: i32,",
        "}",
        "",
        "#[repr(C)]",
        "#[derive(Clone, Copy, Debug)]",
        "pub struct DivideVector {",
        "    pub numerator: i32,",
        "    pub denominator: i32,",
        "    pub shift: u8,",
        "    pub expected: i32,",
        "}",
        "",
        "#[repr(C)]",
        "#[derive(Clone, Copy, Debug)]",
        "pub struct InterpolationVector {",
        "    pub altitude_q12: i32,",
        "    pub density_q28: i32,",
        "    pub gravity_q28: i32,",
        "}",
        "",
        "pub const MULTIPLY_VECTORS: &[MultiplyVector] = &[",
    ]
    for vector in arithmetic["multiply_scaled"]:
        lines.append(
            "    MultiplyVector { "
            f"a: {rust_i32(vector['a'])}, "
            f"b: {rust_i32(vector['b'])}, "
            f"shift: {vector['shift']}, "
            f"expected: {rust_i32(vector['expected'])} "
            "},"
        )
    lines.extend(["];"])
    lines.extend(["", "pub const DIVIDE_VECTORS: &[DivideVector] = &["])
    for vector in arithmetic["divide_scaled"]:
        lines.append(
            "    DivideVector { "
            f"numerator: {rust_i32(vector['numerator'])}, "
            f"denominator: {rust_i32(vector['denominator'])}, "
            f"shift: {vector['shift']}, "
            f"expected: {rust_i32(vector['expected'])} "
            "},"
        )
    lines.extend(["];"])
    lines.extend(["", "pub const INTERPOLATION_VECTORS: &[InterpolationVector] = &["])
    for vector in arithmetic["interpolation"]:
        lines.append(
            "    InterpolationVector { "
            f"altitude_q12: {rust_i32(vector['altitude_q12'])}, "
            f"density_q28: {rust_i32(vector['density_q28'])}, "
            f"gravity_q28: {rust_i32(vector['gravity_q28'])} "
            "},"
        )
    lines.extend(["];"])

    for name, values in (
        ("ALTITUDE_KNOTS_Q12", environment["altitude_knots_q12"]),
        ("DENSITY_Q28", environment["density_q28"]),
        ("GRAVITY_Q28", environment["gravity_q28"]),
    ):
        rendered = ", ".join(rust_i32(value) for value in values)
        lines.extend(["", f"pub const {name}: &[i32] = &[{rendered}];"])

    return "\n".join(lines) + "\n"


def emit_cpp(document: dict[str, Any]) -> str:
    arithmetic = document["arithmetic"]
    environment = document["environment"]
    lines = [
        "// Generated by phase0/reference/emit_candidate_vectors.py.",
        "// Do not edit by hand.",
        "#ifndef KSA64_PHASE0_VECTORS_HPP",
        "#define KSA64_PHASE0_VECTORS_HPP",
        "",
        "#define KSA64_I32_MIN (-2147483647L - 1L)",
        "#define KSA64_I32_MAX 2147483647L",
        "",
        "struct MultiplyVector {",
        "    long a;",
        "    long b;",
        "    unsigned char shift;",
        "    long expected;",
        "};",
        "",
        "struct DivideVector {",
        "    long numerator;",
        "    long denominator;",
        "    unsigned char shift;",
        "    long expected;",
        "};",
        "",
        "struct InterpolationVector {",
        "    long altitude_q12;",
        "    long density_q28;",
        "    long gravity_q28;",
        "};",
        "",
        "static const MultiplyVector MULTIPLY_VECTORS[] = {",
    ]
    for vector in arithmetic["multiply_scaled"]:
        lines.append(
            "    { "
            f"{cpp_long(vector['a'])}, "
            f"{cpp_long(vector['b'])}, "
            f"{vector['shift']}, "
            f"{cpp_long(vector['expected'])} "
            "},"
        )
    lines.extend(["};", ""])
    lines.append("static const DivideVector DIVIDE_VECTORS[] = {")
    for vector in arithmetic["divide_scaled"]:
        lines.append(
            "    { "
            f"{cpp_long(vector['numerator'])}, "
            f"{cpp_long(vector['denominator'])}, "
            f"{vector['shift']}, "
            f"{cpp_long(vector['expected'])} "
            "},"
        )
    lines.extend(["};", ""])
    lines.append("static const InterpolationVector INTERPOLATION_VECTORS[] = {")
    for vector in arithmetic["interpolation"]:
        lines.append(
            "    { "
            f"{cpp_long(vector['altitude_q12'])}, "
            f"{cpp_long(vector['density_q28'])}, "
            f"{cpp_long(vector['gravity_q28'])} "
            "},"
        )
    lines.extend(["};"])

    for name, values in (
        ("ALTITUDE_KNOTS_Q12", environment["altitude_knots_q12"]),
        ("DENSITY_Q28", environment["density_q28"]),
        ("GRAVITY_Q28", environment["gravity_q28"]),
    ):
        rendered = ", ".join(cpp_long(value) for value in values)
        lines.extend(["", f"static const long {name}[] = {{ {rendered} }};"])

    lines.extend(
        [
            "",
            "#define MULTIPLY_VECTOR_COUNT (sizeof(MULTIPLY_VECTORS) / sizeof(MULTIPLY_VECTORS[0]))",
            "#define DIVIDE_VECTOR_COUNT (sizeof(DIVIDE_VECTORS) / sizeof(DIVIDE_VECTORS[0]))",
            "#define INTERPOLATION_VECTOR_COUNT (sizeof(INTERPOLATION_VECTORS) / sizeof(INTERPOLATION_VECTORS[0]))",
            "#define ENVIRONMENT_KNOT_COUNT (sizeof(ALTITUDE_KNOTS_Q12) / sizeof(ALTITUDE_KNOTS_Q12[0]))",
            "",
            "#endif",
        ]
    )
    return "\n".join(lines) + "\n"


def outputs() -> dict[Path, bytes]:
    document = load_document()
    return {
        RUST_PATH: emit_rust(document).encode("utf-8"),
        CPP_PATH: emit_cpp(document).encode("utf-8"),
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    arguments = parser.parse_args()

    generated = outputs()
    if arguments.check:
        stale = [path for path, payload in generated.items() if not path.exists() or path.read_bytes() != payload]
        if stale:
            print("Generated candidate bindings are stale or missing:", file=sys.stderr)
            for path in stale:
                print(f"  {path}", file=sys.stderr)
            return 1
        print("Phase 0 candidate bindings are current")
        return 0

    for path, payload in generated.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(payload)
        print(f"Wrote {path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
