#!/usr/bin/env python3
"""Emit deterministic Rust and C++ bindings for the Phase 0 vertical gate."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any


PROJECT_ROOT = Path(__file__).resolve().parents[2]
INPUT_PATH = PROJECT_ROOT / "phase0" / "vectors" / "phase0-v1.json"
RUST_PATH = PROJECT_ROOT / "phase0" / "generated" / "phase0_vertical.rs"
CPP_PATH = PROJECT_ROOT / "phase0" / "generated" / "phase0_vertical.hpp"

RAW_CONSTANTS = (
    "burn_duration_q12",
    "cda_q16",
    "dry_mass_q12",
    "initial_mass_q12",
    "initial_propellant_q12",
    "mass_flow_q12",
    "thrust_q12",
    "timestep_q12",
)


def load_document() -> dict[str, Any]:
    return json.loads(INPUT_PATH.read_text(encoding="utf-8"))


def rust_i32(value: int) -> str:
    if value == -(1 << 31):
        return "i32::MIN"
    if value == (1 << 31) - 1:
        return "i32::MAX"
    return str(value)


def cpp_long(value: int) -> str:
    if value == -(1 << 31):
        return "KSA64_I32_MIN"
    if value == (1 << 31) - 1:
        return "KSA64_I32_MAX"
    return f"{value}L"


def emit_rust(document: dict[str, Any]) -> str:
    raw_constants = document["constants"]["raw"]
    vertical = document["vertical"]
    lines = [
        "// Generated by phase0/reference/emit_vertical_bindings.py.",
        "// Do not edit by hand.",
        "",
        "#[repr(C)]",
        "#[derive(Clone, Copy, Debug)]",
        "pub struct VerticalCheckpoint {",
        "    pub step: u16,",
        "    pub time_q12: i32,",
        "    pub altitude_q12: i32,",
        "    pub velocity_q24: i32,",
        "    pub acceleration_q28: i32,",
        "    pub mass_q12: i32,",
        "    pub propellant_q12: i32,",
        "    pub engine_active: u8,",
        "    pub cutoff_events: u8,",
        "}",
        "",
    ]
    for name in RAW_CONSTANTS:
        lines.append(f"pub const {name.upper()}: i32 = {rust_i32(raw_constants[name])};")
    lines.extend(
        [
            f"pub const VERTICAL_TOTAL_STEPS: u16 = {vertical['total_steps']};",
            f"pub const VERTICAL_FINAL_FNV1A32: u32 = {vertical['final_fnv1a32']};",
            "",
            "pub const VERTICAL_CHECKPOINTS: &[VerticalCheckpoint] = &[",
        ]
    )
    for checkpoint in vertical["fixed_checkpoints"]:
        raw = checkpoint["raw"]
        lines.append(
            "    VerticalCheckpoint { "
            f"step: {checkpoint['step']}, "
            f"time_q12: {rust_i32(raw['time_q12'])}, "
            f"altitude_q12: {rust_i32(raw['altitude_q12'])}, "
            f"velocity_q24: {rust_i32(raw['velocity_q24'])}, "
            f"acceleration_q28: {rust_i32(raw['acceleration_q28'])}, "
            f"mass_q12: {rust_i32(raw['mass_q12'])}, "
            f"propellant_q12: {rust_i32(raw['propellant_q12'])}, "
            f"engine_active: {raw['engine_active']}, "
            f"cutoff_events: {raw['cutoff_events']} "
            "},"
        )
    lines.extend(["];"])
    return "\n".join(lines) + "\n"


def emit_cpp(document: dict[str, Any]) -> str:
    raw_constants = document["constants"]["raw"]
    vertical = document["vertical"]
    lines = [
        "// Generated by phase0/reference/emit_vertical_bindings.py.",
        "// Do not edit by hand.",
        "#ifndef KSA64_PHASE0_VERTICAL_HPP",
        "#define KSA64_PHASE0_VERTICAL_HPP",
        "",
        "struct VerticalCheckpoint {",
        "    unsigned step;",
        "    long time_q12;",
        "    long altitude_q12;",
        "    long velocity_q24;",
        "    long acceleration_q28;",
        "    long mass_q12;",
        "    long propellant_q12;",
        "    unsigned char engine_active;",
        "    unsigned char cutoff_events;",
        "};",
        "",
    ]
    for name in RAW_CONSTANTS:
        lines.append(f"static const long {name.upper()} = {cpp_long(raw_constants[name])};")
    lines.extend(
        [
            f"static const unsigned VERTICAL_TOTAL_STEPS = {vertical['total_steps']};",
            f"static const unsigned long VERTICAL_FINAL_FNV1A32 = {vertical['final_fnv1a32']}UL;",
            "",
            "static const VerticalCheckpoint VERTICAL_CHECKPOINTS[] = {",
        ]
    )
    for checkpoint in vertical["fixed_checkpoints"]:
        raw = checkpoint["raw"]
        lines.append(
            "    { "
            f"{checkpoint['step']}, "
            f"{cpp_long(raw['time_q12'])}, "
            f"{cpp_long(raw['altitude_q12'])}, "
            f"{cpp_long(raw['velocity_q24'])}, "
            f"{cpp_long(raw['acceleration_q28'])}, "
            f"{cpp_long(raw['mass_q12'])}, "
            f"{cpp_long(raw['propellant_q12'])}, "
            f"{raw['engine_active']}, "
            f"{raw['cutoff_events']} "
            "},"
        )
    lines.extend(
        [
            "};",
            "",
            "#define VERTICAL_CHECKPOINT_COUNT (sizeof(VERTICAL_CHECKPOINTS) / sizeof(VERTICAL_CHECKPOINTS[0]))",
            "",
            "#endif",
        ]
    )
    return "\n".join(lines) + "\n"


def outputs() -> dict[Path, bytes]:
    document = load_document()
    return {
        RUST_PATH: emit_rust(document).encode("utf-8"),
        CPP_PATH: emit_cpp(document).encode("utf-8"),
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    arguments = parser.parse_args()
    generated = outputs()

    if arguments.check:
        stale = [
            path
            for path, payload in generated.items()
            if not path.exists() or path.read_bytes() != payload
        ]
        if stale:
            print("Generated vertical bindings are stale or missing:", file=sys.stderr)
            for path in stale:
                print(f"  {path}", file=sys.stderr)
            return 1
        print("Phase 0 vertical bindings are current")
        return 0

    for path, payload in generated.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(payload)
        print(f"Wrote {path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
