#!/usr/bin/env python3
"""Pack the reviewed Phase 2 mission scenarios and reference evidence."""

from __future__ import annotations

import argparse
import hashlib
import json
import struct
import sys
import zlib
from decimal import Decimal, ROUND_HALF_UP
from pathlib import Path
from typing import Any

import mission_reference


IMAGE_LENGTH = 884
HEADER_LENGTH = 64
STAGE_RECORD_LENGTH = 40
PITCH_RECORD_LENGTH = 8
AERO_RECORD_LENGTH = 132
MAX_STAGES = 4
MAX_PITCH_KNOTS = 16
MAX_AERO_TABLES = 4
MAX_AERO_KNOTS = 16
PITCH_BASE = HEADER_LENGTH + MAX_STAGES * STAGE_RECORD_LENGTH
AERO_BASE = PITCH_BASE + MAX_PITCH_KNOTS * PITCH_RECORD_LENGTH


def rounded(value: Decimal) -> int:
    return int(value.to_integral_value(rounding=ROUND_HALF_UP))


def fixed(value: str | int, bits: int) -> int:
    return rounded(Decimal(str(value)) * (1 << bits))


def fnv1a(text: str) -> int:
    value = 2_166_136_261
    for byte in text.encode():
        value = ((value ^ byte) * 16_777_619) & 0xFFFF_FFFF
    return value


def steps(value: str | int, timestep: Decimal) -> int:
    count = Decimal(str(value)) / timestep
    if count != count.to_integral_value():
        raise ValueError(f"event {value} is not timestep aligned")
    return int(count)


def pack_scenario(source: dict[str, Any], scenario_id: str, stage2_scale: Decimal, flags: int) -> bytes:
    timestep = Decimal(source["timestep_s"])
    stage_count = len(source["stages"])
    pitch_count = len(source["pitch_program"])
    aero_names = list(source["aerodynamics"])
    if stage_count > MAX_STAGES or pitch_count > MAX_PITCH_KNOTS or len(aero_names) > MAX_AERO_TABLES:
        raise ValueError("fixed-capacity limit exceeded")
    image = bytearray(IMAGE_LENGTH)
    struct.pack_into("<4sHHIIIiI HBBBBH iiii", image, 0,
        b"KSC2", 2, IMAGE_LENGTH,
        fnv1a(source["numeric_contract"]), fnv1a(scenario_id), fnv1a(source["environment"]),
        fixed(source["timestep_s"], 16), steps(source["duration_s"], timestep),
        source["telemetry_stride_steps"], stage_count, pitch_count, len(aero_names), flags, 0,
        fixed(source["payload_mass_t"], 12), fixed(source["initial"]["altitude_km"], 12),
        fixed(source["initial"]["radial_velocity_km_s"], 24),
        fixed(source["initial"]["surface_relative_velocity_km_s"], 24))

    for index, stage in enumerate(source["stages"]):
        burn_steps = steps(stage["max_burn_s"], timestep)
        if index == 1:
            burn_steps = rounded(Decimal(burn_steps) * stage2_scale)
        offset = HEADER_LENGTH + index * STAGE_RECORD_LENGTH
        struct.pack_into("<iiiiIHH iBB", image, offset,
            fixed(stage["dry_mass_t"], 12), fixed(stage["propellant_mass_t"], 12),
            fixed(stage["thrust_mn"], 12), fixed(stage["mass_flow_t_s"], 16), burn_steps,
            steps(stage["separation_delay_s"], timestep), steps(stage["ignition_delay_s"], timestep),
            fixed(stage["reference_area_m2"], 16), aero_names.index(stage["aero_table"]),
            1 if stage["separate"] else 0)

    pitch_base = HEADER_LENGTH + MAX_STAGES * STAGE_RECORD_LENGTH
    for index, knot in enumerate(source["pitch_program"]):
        offset = pitch_base + index * PITCH_RECORD_LENGTH
        angle = rounded(Decimal(knot["degrees_from_vertical"]) * Decimal(65536) / Decimal(360))
        struct.pack_into("<iHH", image, offset, fixed(knot["time_s"], 16), angle, 0)

    aero_base = pitch_base + MAX_PITCH_KNOTS * PITCH_RECORD_LENGTH
    for table_index, name in enumerate(aero_names):
        table = source["aerodynamics"][name]
        if len(table) > MAX_AERO_KNOTS:
            raise ValueError("aerodynamic knot limit exceeded")
        offset = aero_base + table_index * AERO_RECORD_LENGTH
        struct.pack_into("<B3x", image, offset, len(table))
        for knot_index, knot in enumerate(table):
            struct.pack_into("<ii", image, offset + 4 + knot_index * 8,
                fixed(knot["mach"], 16), fixed(knot["cd"], 14))

    struct.pack_into("<I", image, IMAGE_LENGTH - 4, zlib.crc32(image[:-4]) & 0xFFFF_FFFF)
    return bytes(image)


def rust_fixture_source(source: dict[str, Any], nominal: bytes, failure: bytes) -> bytes:
    def i32(offset: int) -> int:
        return struct.unpack_from("<i", nominal, offset)[0]

    def u16(offset: int) -> int:
        return struct.unpack_from("<H", nominal, offset)[0]

    stage_fields = {
        "STAGE_DRY_Q12": 0,
        "STAGE_PROPELLANT_Q12": 4,
        "STAGE_THRUST_Q12": 8,
        "STAGE_MASS_FLOW_Q16": 12,
        "STAGE_AREA_Q16": 24,
    }
    lines = [
        "// Generated by phase2/reference/generate_mission.py.",
        "// Do not edit by hand.",
        "",
        f"pub const NOMINAL_SCENARIO_ID: u32 = {fnv1a(source['scenario_id'])};",
        f"pub const FAILURE_SCENARIO_ID: u32 = {fnv1a('ksa64.phase2.ksa2a-early-cutoff.v1')};",
        f"pub const TIMESTEP_Q16: i32 = {i32(20)};",
        f"pub const MISSION_STEPS: u32 = {struct.unpack_from('<I', nominal, 24)[0]};",
        f"pub const TELEMETRY_STRIDE: u16 = {u16(28)};",
        f"pub const PAYLOAD_Q12: i32 = {i32(36)};",
    ]
    for name, field_offset in stage_fields.items():
        values = [i32(HEADER_LENGTH + index * STAGE_RECORD_LENGTH + field_offset) for index in range(len(source["stages"]))]
        lines.append(f"pub const {name}: [i32; 2] = {values};")
    lines.extend([
        f"pub const NOMINAL_BURN_STEPS: [u32; 2] = {[struct.unpack_from('<I', nominal, HEADER_LENGTH + i * STAGE_RECORD_LENGTH + 16)[0] for i in range(2)]};",
        f"pub const FAILURE_BURN_STEPS: [u32; 2] = {[struct.unpack_from('<I', failure, HEADER_LENGTH + i * STAGE_RECORD_LENGTH + 16)[0] for i in range(2)]};",
        f"pub const SEPARATION_STEPS: [u16; 2] = {[u16(HEADER_LENGTH + i * STAGE_RECORD_LENGTH + 20) for i in range(2)]};",
        f"pub const IGNITION_STEPS: [u16; 2] = {[u16(HEADER_LENGTH + i * STAGE_RECORD_LENGTH + 22) for i in range(2)]};",
        f"pub const AERO_INDEX: [u8; 2] = {[nominal[HEADER_LENGTH + i * STAGE_RECORD_LENGTH + 28] for i in range(2)]};",
        f"pub const SEPARATE: [bool; 2] = {[bool(nominal[HEADER_LENGTH + i * STAGE_RECORD_LENGTH + 29]) for i in range(2)]};".replace("True", "true").replace("False", "false"),
    ])
    pitch_count = nominal[31]
    lines.append(f"pub const PITCH_TIME_Q16: [i32; {pitch_count}] = {[i32(PITCH_BASE + i * PITCH_RECORD_LENGTH) for i in range(pitch_count)]};")
    lines.append(f"pub const PITCH_ANGLE: [u16; {pitch_count}] = {[u16(PITCH_BASE + i * PITCH_RECORD_LENGTH + 4) for i in range(pitch_count)]};")
    aero_count = nominal[32]
    counts = [nominal[AERO_BASE + index * AERO_RECORD_LENGTH] for index in range(aero_count)]
    lines.append(f"pub const AERO_COUNT: [u8; {aero_count}] = {counts};")
    for table in range(aero_count):
        offset = AERO_BASE + table * AERO_RECORD_LENGTH + 4
        mach = [i32(offset + knot * 8) for knot in range(MAX_AERO_KNOTS)]
        cd = [i32(offset + knot * 8 + 4) for knot in range(MAX_AERO_KNOTS)]
        lines.append(f"pub const AERO_{table}_MACH_Q16: [i32; 16] = {mach};")
        lines.append(f"pub const AERO_{table}_CD_Q14: [i32; 16] = {cd};")
    lines.append("")
    return ("\n".join(lines)).encode()

def outputs(root: Path) -> dict[Path, bytes]:
    source = json.loads((root / "phase2/examples/ksa2a-200km.json").read_text())
    nominal = pack_scenario(source, source["scenario_id"], Decimal("1"), 0)
    failure_id = "ksa64.phase2.ksa2a-early-cutoff.v1"
    failure = pack_scenario(source, failure_id, Decimal("0.95"), 1)
    nominal_reference = mission_reference.simulate()
    failure_reference = mission_reference.simulate(stage2_scale=0.95)
    evidence = {
        "model": "independent float64 semi-implicit polar reference",
        "timestep_s": source["timestep_s"],
        "nominal_scenario_id": source["scenario_id"],
        "failure_scenario_id": failure_id,
        "nominal": nominal_reference,
        "early_cutoff": failure_reference,
        "acceptance": {
            "nominal_perigee_km": [180, 220],
            "nominal_apogee_km": [180, 220],
            "nominal_max_eccentricity": 0.01,
            "nominal_max_q_kpa": 60,
            "nominal_max_proper_acceleration_m_s2": 60,
            "failure_must_not_be_stable": True,
        },
        "packed": {
            "nominal_crc32": f"0x{struct.unpack_from('<I', nominal, IMAGE_LENGTH - 4)[0]:08x}",
            "failure_crc32": f"0x{struct.unpack_from('<I', failure, IMAGE_LENGTH - 4)[0]:08x}",
            "image_length": IMAGE_LENGTH,
        },
    }
    result = {
        root / "phase2/examples/ksa2a-200km.ksc2": nominal,
        root / "phase2/examples/ksa2a-early-cutoff.ksc2": failure,
        root / "phase2/mission-reference-v1.json": (json.dumps(evidence, indent=2) + "\n").encode(),
        root / "phase2/generated/mission_v1.rs": rust_fixture_source(source, nominal, failure),
    }
    for path, data in list(result.items()):
        result[path.with_name(path.name + ".sha256")] = (hashlib.sha256(data).hexdigest() + "\n").encode()
    return result


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    root = Path(__file__).resolve().parents[2]
    failed = False
    for path, data in outputs(root).items():
        if args.check:
            if not path.exists() or path.read_bytes() != data:
                print(f"stale or missing: {path.relative_to(root)}", file=sys.stderr)
                failed = True
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(data)
            print(path.relative_to(root))
    return 1 if failed else 0


if __name__ == "__main__":
    raise SystemExit(main())
