#!/usr/bin/env python3
"""Freeze selected canonical KST2 records for portable target self-tests."""

from __future__ import annotations

import argparse
import hashlib
import sys
import zlib
from pathlib import Path


HEADER = 40
FRAME = 64


def rust_array(name: str, data: bytes) -> list[str]:
    rows = [", ".join(str(byte) for byte in data[index:index + 16]) for index in range(0, len(data), 16)]
    return [f"pub const {name}: [u8; {len(data)}] = [", *(f"    {row}," for row in rows), "];", ""]


def outputs(root: Path) -> dict[Path, bytes]:
    stream = (root / "phase2/examples/ksa2a-200km.kst2").read_bytes()
    if len(stream) != 57_704 or zlib.crc32(stream) & 0xFFFF_FFFF != 0x7D13_B2BF:
        raise ValueError("canonical KST2 identity changed")
    header = stream[:HEADER]
    initial = stream[HEADER:HEADER + FRAME]
    final = stream[-FRAME:]
    lines = [
        "// Generated by phase2/reference/generate_telemetry_fixture.py.",
        "// Do not edit by hand.",
        "",
        "pub const STREAM_LENGTH: usize = 57_704;",
        "pub const FRAME_COUNT: u32 = 901;",
        "pub const STREAM_CRC32: u32 = 0x7d13_b2bf;",
        "pub const FINAL_STATE_CHECKSUM: u32 = 0xcc57_612b;",
        "",
        *rust_array("HEADER", header),
        *rust_array("INITIAL_FRAME", initial),
        *rust_array("FINAL_FRAME", final),
    ]
    data = ("\n".join(lines)).encode()
    result = {root / "phase2/generated/telemetry_v2.rs": data}
    result[root / "phase2/generated/telemetry_v2.rs.sha256"] = (hashlib.sha256(data).hexdigest() + "\n").encode()
    return result


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    root = Path(__file__).resolve().parents[2]
    failed = False
    for path, data in outputs(root).items():
        if args.check:
            if not path.exists() or path.read_bytes() != data:
                print(f"stale or missing: {path.relative_to(root)}", file=sys.stderr)
                failed = True
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(data)
            print(path.relative_to(root))
    return 1 if failed else 0


if __name__ == "__main__":
    raise SystemExit(main())
