#!/usr/bin/env python3
"""Derive the compact C64 replay tape from canonical Phase 2 KST2 telemetry."""

from __future__ import annotations

import argparse
import hashlib
import struct
import sys
import zlib
from pathlib import Path

HEADER_LENGTH = 40
FRAME_LENGTH = 64
REPLAY_HEADER_LENGTH = 40
REPLAY_RECORD_LENGTH = 3
DISPLAY_ALTITUDE_Q12 = 220 * 4096
EARTH_RADIUS_Q12 = 26_124_849
MISSION_MAX_Q_Q16 = 2_672_500
MISSION_PERIGEE_Q12 = EARTH_RADIUS_Q12 + 770_739
MISSION_APOGEE_Q12 = EARTH_RADIUS_Q12 + 770_739


def build(source: bytes) -> bytes:
    if source[:4] != b"KST2" or len(source) < HEADER_LENGTH + FRAME_LENGTH:
        raise ValueError("not a canonical KST2 stream")
    frame_bytes = len(source) - HEADER_LENGTH
    if frame_bytes % FRAME_LENGTH:
        raise ValueError("truncated KST2 stream")
    frames = [
        source[offset : offset + FRAME_LENGTH]
        for offset in range(HEADER_LENGTH, len(source), FRAME_LENGTH)
    ]
    for frame in frames:
        if zlib.crc32(frame[:60]) & 0xFFFF_FFFF != struct.unpack_from("<I", frame, 60)[0]:
            raise ValueError("KST2 frame CRC mismatch")
    final = frames[-1]
    terminal_downrange = abs(struct.unpack_from("<i", final, 12)[0])
    downrange_scale = max(terminal_downrange // 39, 1)
    altitude_scale = max(DISPLAY_ALTITUDE_Q12 // 10, 1)
    records = bytearray()
    max_q = 0
    for frame in frames:
        radius = struct.unpack_from("<i", frame, 8)[0]
        downrange = abs(struct.unpack_from("<i", frame, 12)[0])
        dynamic_pressure = struct.unpack_from("<i", frame, 48)[0]
        events = struct.unpack_from("<H", frame, 54)[0]
        if events > 0xFF:
            raise ValueError("replay event mask does not fit compact record")
        x = min(downrange // downrange_scale, 39)
        y = min(max(radius - EARTH_RADIUS_Q12, 0) // altitude_scale, 10)
        records.extend((x, y, events))
        max_q = max(max_q, dynamic_pressure)

    scenario_id = struct.unpack_from("<I", source, 16)[0]
    final_checksum = struct.unpack_from("<I", final, 56)[0]
    if max_q > MISSION_MAX_Q_Q16:
        raise ValueError("sampled Max-Q exceeds accepted full-mission Max-Q")
    header = bytearray(REPLAY_HEADER_LENGTH)
    struct.pack_into(
        "<4sHHHHIIIiii",
        header,
        0,
        b"KRP2",
        1,
        REPLAY_HEADER_LENGTH,
        REPLAY_RECORD_LENGTH,
        len(frames),
        zlib.crc32(source) & 0xFFFF_FFFF,
        scenario_id,
        final_checksum,
        MISSION_MAX_Q_Q16,
        MISSION_PERIGEE_Q12,
        MISSION_APOGEE_Q12,
    )
    header[36:40] = struct.pack("<I", zlib.crc32(header[:36]) & 0xFFFF_FFFF)
    tape = bytes(header) + bytes(records) + source[:HEADER_LENGTH] + final
    return tape + struct.pack("<I", zlib.crc32(tape) & 0xFFFF_FFFF)


def rust_crc_table() -> bytes:
    values = []
    for byte in range(256):
        crc = byte
        for _ in range(8):
            crc = (crc >> 1) ^ (0xEDB88320 if crc & 1 else 0)
        values.append(crc)
    lines = [
        "// Generated by phase2/reference/generate_replay.py.",
        "// Do not edit by hand.",
        "pub const CRC32_TABLE: [u32; 256] = [",
    ]
    for offset in range(0, 256, 8):
        row = ", ".join(f"0x{value:08x}" for value in values[offset : offset + 8])
        lines.append(f"    {row},")
    lines.extend(["];", ""])
    return "\n".join(lines).encode()


def outputs(root: Path) -> dict[Path, bytes]:
    source = (root / "phase2/examples/ksa2a-200km.kst2").read_bytes()
    tape = build(source)
    table = rust_crc_table()
    return {
        root / "phase2/examples/ksa2a-200km.krp2": tape,
        root / "phase2/examples/ksa2a-200km.krp2.sha256": (
            hashlib.sha256(tape).hexdigest() + "\n"
        ).encode(),
        root / "phase2/generated/replay_crc32_v1.rs": table,
        root / "phase2/generated/replay_crc32_v1.rs.sha256": (
            hashlib.sha256(table).hexdigest() + "\n"
        ).encode(),
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    root = Path(__file__).resolve().parents[2]
    failed = False
    for path, data in outputs(root).items():
        if args.check:
            if not path.exists() or path.read_bytes() != data:
                print(f"stale or missing: {path.relative_to(root)}", file=sys.stderr)
                failed = True
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(data)
            print(path.relative_to(root))
    return 1 if failed else 0


if __name__ == "__main__":
    raise SystemExit(main())
