#!/usr/bin/env python3
"""Generate the simple rotating-Earth Phase 2 atmosphere tables."""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from decimal import Decimal, ROUND_HALF_UP
from pathlib import Path

ALTITUDE_KM = [0, 2, 5, 10, 15, 20, 30, 40, 50, 70, 100, 120, 200, 300, 500, 750, 1000, 1500, 2000]
DENSITY = ["1.225", "1.0066", "0.73612", "0.41351", "0.19476", "0.08891", "0.01841", "0.003996", "0.001027", "0.0000828", "0.000000533", "0", "0", "0", "0", "0", "0", "0", "0"]
SOUND_KM_S = ["0.340294", "0.33253", "0.32055", "0.29953", "0.29507", "0.29507", "0.30171", "0.31763", "0.32980", "0.29600", "0.27500", "0.27500", "0.27500", "0.27500", "0.27500", "0.27500", "0.27500", "0.27500", "0.27500"]


def raw(value, bits):
    return int((Decimal(str(value)) * (1 << bits)).to_integral_value(rounding=ROUND_HALF_UP))


def rust_array(name, ty, values):
    rows = [", ".join(str(value) for value in values[index:index + 6]) for index in range(0, len(values), 6)]
    return [f"pub const {name}: [{ty}; {len(values)}] = [", *(f"    {row}," for row in rows), "];", ""]


def outputs(root: Path):
    payload = {
        "environment": "earth.rotating-equatorial-simple-atmosphere.v1",
        "model_claim": "deterministic learning table; not a standard-atmosphere implementation",
        "altitude_km": ALTITUDE_KM,
        "density_kg_m3": DENSITY,
        "sound_speed_km_s": SOUND_KM_S,
    }
    lines = ["// Generated by phase2/reference/generate_environment.py.", "// Do not edit by hand.", "", f"pub const TABLE_LENGTH: usize = {len(ALTITUDE_KM)};", ""]
    lines += rust_array("ALTITUDE_KNOTS_Q12", "i32", [raw(value, 12) for value in ALTITUDE_KM])
    lines += rust_array("DENSITY_Q28", "i32", [raw(value, 28) for value in DENSITY])
    lines += rust_array("SOUND_SPEED_Q24", "i32", [raw(value, 24) for value in SOUND_KM_S])
    result = {
        root / "phase2" / "environment-v1.json": (json.dumps(payload, indent=2) + "\n").encode(),
        root / "phase2" / "generated" / "environment_v1.rs": ("\n".join(lines)).encode(),
    }
    for path, data in list(result.items()):
        result[path.with_name(path.name + ".sha256")] = (hashlib.sha256(data).hexdigest() + "\n").encode()
    return result


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    root = Path(__file__).resolve().parents[2]
    failed = False
    for path, data in outputs(root).items():
        if args.check:
            if not path.exists() or path.read_bytes() != data:
                print(f"stale: {path.relative_to(root)}", file=sys.stderr)
                failed = True
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(data)
            print(path.relative_to(root))
    return 1 if failed else 0


if __name__ == "__main__":
    raise SystemExit(main())
