[workspace]
members = ["core", "flight", "host", "interface", "sim"]
exclude = ["third_party/clap", "third_party/anstyle"]
resolver = "2"

[profile.release]
opt-level = 2
lto = true
panic = "abort"
[profile.c64]
inherits = "release"
opt-level = "z"
codegen-units = 1

[patch.crates-io]
anstyle = { path = "third_party/anstyle/crates/anstyle" }
