#!/usr/bin/env python3
"""Generate the Phase 9.5 advanced-effector fixed-point contract."""
from __future__ import annotations
import json, math, sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
SOURCE=ROOT/'phase9_5'/'numeric-contract.json'
OUTPUT=ROOT/'phase9_5'/'generated'/'numeric_v1.rs'
SIGNED_MAX=2**31-1

def fnv1a32(text: str) -> int:
    value=2166136261
    for byte in text.encode('ascii'):
        value=((value^byte)*16777619)&0xffffffff
    return value

def bits(maximum: float, headroom: int) -> int:
    allowed=SIGNED_MAX*(100-headroom)/100
    return math.floor(math.log2(allowed/maximum))

def main() -> None:
    source=json.loads(SOURCE.read_text(encoding='utf-8'))
    specs=[('EFFECTOR_FORCE','effector_force_n'),('HINGE_MOMENT','hinge_moment_nm'),('SUPPLY_PRESSURE','supply_pressure_pa'),('PULSE_IMPULSE','pulse_impulse_ns'),('MASS_FLOW','mass_flow_kgps'),('SUPPLY_SCALE','supply_scale')]
    rows=[]
    for name,key in specs:
        maximum=max(abs(float(v)) for v in source['envelopes'][key])
        fractional=bits(maximum,source['headroom_percent'])
        raw=round(maximum*(1<<fractional))
        assert raw<=SIGNED_MAX*3//4
        rows.append((name,fractional,raw))
    out=['// Generated by phase9_5/reference/generate_numeric.py. Do not edit by hand.',f'pub const ADVANCED_EFFECTOR_NUMERIC_CONTRACT: &str = "{source["contract"]}";',f'pub const ADVANCED_EFFECTOR_NUMERIC_CONTRACT_ID: u32 = 0x{fnv1a32(source["contract"]):08x};','pub const BODY_TORQUE_DEMAND_FRACTIONAL_BITS: u8 = 12;','pub const ADVANCED_TIME_FRACTIONAL_BITS: u8 = 18;','pub const RCS_PULSE_QUANTUM_Q18: i32 = 1_024;','']
    for name,fractional,_ in rows: out.append(f'pub const ADVANCED_{name}_FRACTIONAL_BITS: u8 = {fractional};')
    out.append('')
    for name,_,raw in rows: out.append(f'pub const ADVANCED_MAX_{name}_RAW: i32 = {raw:_};')
    rendered='\n'.join(out)+'\n'
    if '--check' in sys.argv:
        if OUTPUT.read_text(encoding='utf-8')!=rendered: raise SystemExit(f'stale generated file: {OUTPUT}')
    else:
        OUTPUT.parent.mkdir(parents=True,exist_ok=True); OUTPUT.write_text(rendered,encoding='utf-8',newline='\n')
if __name__=='__main__': main()
