//! Frozen Phase 5 numeric, scenario, and compatibility identities.
//!
//! The source of truth is `phase5/contract-v1.json`. The included Rust file is
//! generated by `phase5/reference/generate_contract.py`.

include!("../../phase5/generated/contract_v1.rs");

/// The complete immutable evidence binding inherited by Phase 5.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct PlanarCompatibilityEvidence {
    pub phase2_state_checksum: u32,
    pub phase3_truth_checksum: u32,
    pub phase3_sensor_checksum: u32,
    pub phase3_navigation_checksum: u32,
    pub phase3_flight_checksum: u32,
    pub phase3_telemetry_crc32: u32,
}

pub const PHASE5_PLANAR_COMPATIBILITY: PlanarCompatibilityEvidence = PlanarCompatibilityEvidence {
    phase2_state_checksum: PHASE5_PLANAR_PHASE2_CHECKSUM,
    phase3_truth_checksum: PHASE5_PLANAR_TRUTH_CHECKSUM,
    phase3_sensor_checksum: PHASE5_PLANAR_SENSOR_CHECKSUM,
    phase3_navigation_checksum: PHASE5_PLANAR_NAV_CHECKSUM,
    phase3_flight_checksum: PHASE5_PLANAR_FLIGHT_CHECKSUM,
    phase3_telemetry_crc32: PHASE5_PLANAR_KST3_CRC32,
};

pub const fn phase5_cadence_is_valid() -> bool {
    PHASE5_ATTITUDE_SUBSTEPS != 0
        && PHASE5_MISSION_STEP_Q16 > 0
        && PHASE5_FAST_STEP_Q16 > 0
        && PHASE5_MISSION_STEP_Q16 == PHASE5_FAST_STEP_Q16 * PHASE5_ATTITUDE_SUBSTEPS as i32
}
