use ksa64_flight::phase5_guidance::reference_guidance_target;
use std::{fmt::Write, path::PathBuf};
fn i16c(v: i32) -> i16 {
    v.clamp(i16::MIN as i32, i16::MAX as i32) as i16
}
fn mix(mut h: u32, v: i16) -> u32 {
    for b in v.to_le_bytes() {
        h = h.rotate_left(5) ^ b as u32;
        h = h.wrapping_add(0x9e37_79b9)
    }
    h
}
fn main() {
    let mut rows = Vec::new();
    let mut sig = 2_166_136_261u32;
    for second in 0..398u32 {
        let a = reference_guidance_target(second * 8);
        let b = reference_guidance_target((second + 1) * 8);
        let start = [
            i16c(a.attitude_q30[1] >> 15),
            i16c(a.attitude_q30[2] >> 15),
            i16c(a.attitude_q30[3] >> 15),
        ];
        let end = [
            i16c(b.attitude_q30[1] >> 15),
            i16c(b.attitude_q30[2] >> 15),
            i16c(b.attitude_q30[3] >> 15),
        ];
        let rate = [
            i16c(a.angular_rate_q24[0] >> 12),
            i16c(a.angular_rate_q24[1] >> 12),
            i16c(a.angular_rate_q24[2] >> 12),
        ];
        for v in start.into_iter().chain(end).chain(rate) {
            sig = mix(sig, v)
        }
        rows.push((start, end, rate));
    }
    let mut out = String::from(
        "// Generated by sim/examples/phase6_guidance_generate.rs; do not hand edit.\n",
    );
    writeln!(
        out,
        "pub const REALTIME_GUIDANCE_SIGNATURE:u32=0x{sig:08x};"
    )
    .unwrap();
    writeln!(
        out,
        "pub const REALTIME_GUIDANCE_SLICES:[RealtimeGuidanceSlice;{}]=[",
        rows.len()
    )
    .unwrap();
    for (start, end, rate) in rows {
        writeln!(
            out,
            " RealtimeGuidanceSlice{{start:{start:?},end:{end:?},rate:{rate:?}}},"
        )
        .unwrap()
    }
    out.push_str("];\n");
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../flight/src/generated/phase6_guidance_v1.rs");
    std::fs::write(path, out).unwrap();
}
