#!/usr/bin/env python3
"""Generate independent exact-arithmetic vectors for Phase 8 aerodynamics."""

from __future__ import annotations

import math
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
OUTPUT = ROOT / "phase8" / "generated" / "aero_vectors_v1.rs"


def q(value: float, bits: int) -> int:
    return round(value * (1 << bits))


def mul_scaled(a: int, b: int, bits: int) -> int:
    return (a * b + (1 << (bits - 1))) >> bits

def div_scaled(numerator: int, denominator: int, bits: int) -> int:
    shifted = numerator << bits
    quotient, remainder = divmod(shifted, denominator)
    return quotient + int(remainder >= denominator - remainder)

def aoa_vector(degrees: float) -> tuple[list[int], int]:
    velocity = [q(100.0, 19), q(100.0 * math.tan(math.radians(degrees)), 19), 0]
    lateral = math.isqrt(velocity[1] ** 2 + velocity[2] ** 2)
    ratio = div_scaled(lateral, velocity[0], 28)
    squared = mul_scaled(ratio, ratio, 28)
    cubed = mul_scaled(squared, ratio, 28)
    return velocity, ratio - cubed // 3


def main() -> None:
    vectors = [aoa_vector(value) for value in (0.0, 5.0, 10.0, 15.0)]
    aoa16, _ = aoa_vector(16.0)
    mach02 = q(0.2, 24)
    mach0 = q(0.0, 24)
    mach04 = q(0.4, 24)
    cd0 = q(0.60, 24)
    cd04 = q(0.58, 24)
    fraction = ((mach02 - mach0) << 16) // (mach04 - mach0)
    cd02 = cd0 + ((cd04 - cd0) * fraction >> 16)
    lines = [
        "// Generated by phase8/reference/generate_aero_vectors.py. Do not edit.",
        "#[derive(Clone, Copy)]",
        "pub struct AoaVector { pub velocity_q19: [i32; 3], pub expected_q28: i32 }",
        "pub const AOA_VECTORS: &[AoaVector] = &[",
    ]
    for velocity, expected in vectors:
        lines.append(f"    AoaVector {{ velocity_q19: {velocity}, expected_q28: {expected} }},")
    lines += [
        "];",
        f"pub const AOA_16_VELOCITY_Q19: [i32; 3] = {aoa16};",
        f"pub const MACH_02_Q24: i32 = {mach02};",
        f"pub const CD_02_Q24: i32 = {cd02};",
    ]
    rendered = "\n".join(lines) + "\n"
    if "--check" in sys.argv:
        if OUTPUT.read_text(encoding="utf-8") != rendered:
            raise SystemExit(f"stale generated file: {OUTPUT}")
    else:
        OUTPUT.write_text(rendered, encoding="utf-8", newline="\n")


if __name__ == "__main__":
    main()
