#!/usr/bin/env python3
"""Generate independent deterministic wind vectors for Phase 8."""
from __future__ import annotations
import math
import sys
from pathlib import Path

ROOT=Path(__file__).resolve().parents[2]
OUTPUT=ROOT/'phase8/generated/wind_vectors_v1.rs'
IDENTITY=0x12345678
GUST_SEED=0x10203040
CASE_SEED=0x4B534138
CADENCE=1<<18
AMP_E=3<<22
AMP_N=2<<22
MAX_GUST=4<<22


def mix32(value:int)->int:
    value &= 0xffffffff
    value ^= value>>16; value=(value*0x7feb352d)&0xffffffff
    value ^= value>>15; value=(value*0x846ca68b)&0xffffffff
    return (value^(value>>16))&0xffffffff


def rol(value:int,bits:int)->int:
    return ((value<<bits)|(value>>(32-bits)))&0xffffffff


def mul(a:int,b:int,bits:int)->int:
    negative=(a<0)^(b<0); value=(abs(a)*abs(b)+(1<<(bits-1)))>>bits
    return -value if negative else value


def div(n:int,d:int,bits:int)->int:
    negative=(n<0)^(d<0); shifted=abs(n)<<bits; q,r=divmod(shifted,abs(d)); q+=int(r>=abs(d)-r)
    return -q if negative else q


def target(epoch:int,axis:int,amp:int)->int:
    key=IDENTITY^rol(GUST_SEED,7)^rol(CASE_SEED,13)^((epoch*0x9e3779b9)&0xffffffff)^((axis*0x85ebca6b)&0xffffffff)
    signed=(mix32(key)&0xffff)-32768
    return max(-MAX_GUST,min(MAX_GUST,mul(amp,signed,15)))


def clamp(v:tuple[int,int,int])->tuple[int,int,int]:
    magnitude=math.isqrt(sum(x*x for x in v))
    if magnitude<=MAX_GUST:return v
    scale=div(MAX_GUST,magnitude,30)
    return tuple(mul(x,scale,30) for x in v)


def sample(altitude_raw:int,time_raw:int)->tuple[tuple[int,int,int],tuple[int,int,int],tuple[int,int,int]]:
    fraction_alt=div(altitude_raw,1000<<13,16)
    mean=( (1<<22)+mul(4<<22,fraction_alt,16), (-2<<22)+mul(4<<22,fraction_alt,16), 0 )
    epoch=time_raw//CADENCE; fraction=div(time_raw%CADENCE,CADENCE,16)
    current=clamp((target(epoch,0,AMP_E),target(epoch,1,AMP_N),0))
    nxt=clamp((target(epoch+1,0,AMP_E),target(epoch+1,1,AMP_N),0))
    gust=tuple(a+mul(b-a,fraction,16) for a,b in zip(current,nxt))
    total=tuple(a+b for a,b in zip(mean,gust))
    return mean,gust,total


def main()->None:
    cases=[(500<<13,0),(500<<13,1<<17),(750<<13,(13*CADENCE)//10)]
    lines=['// Generated by phase8/reference/generate_wind_vectors.py. Do not edit.',
           f'pub const IDENTITY: u32 = 0x{IDENTITY:08x};',f'pub const GUST_SEED: u32 = 0x{GUST_SEED:08x};',f'pub const CASE_SEED: u32 = 0x{CASE_SEED:08x};',
           '#[derive(Clone, Copy)]','pub struct WindVector { pub altitude_q13: i32, pub time_q18: i32, pub mean_q22: [i32;3], pub gust_q22: [i32;3], pub total_q22: [i32;3] }','pub const WIND_VECTORS: &[WindVector] = &[']
    for altitude,time in cases:
        mean,gust,total=sample(altitude,time)
        lines.append(f'    WindVector {{ altitude_q13: {altitude}, time_q18: {time}, mean_q22: {list(mean)}, gust_q22: {list(gust)}, total_q22: {list(total)} }},')
    lines.append('];')
    rendered='\n'.join(lines)+'\n'
    if '--check' in sys.argv:
        if OUTPUT.read_text(encoding='utf-8')!=rendered: raise SystemExit(f'stale generated file: {OUTPUT}')
    else: OUTPUT.write_text(rendered,encoding='utf-8',newline='\n')
if __name__=='__main__':main()
