#!/usr/bin/env python3
"""Generate and verify the Phase 8 hobby-spatial numeric contract."""

from __future__ import annotations

import json
import math
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT / "phase8" / "numeric-contract.json"
OUTPUT = ROOT / "phase8" / "generated" / "numeric_v1.rs"
SIGNED_MAX = 2**31 - 1


def fnv1a32(text: str) -> int:
    value = 2_166_136_261
    for byte in text.encode("ascii"):
        value = ((value ^ byte) * 16_777_619) & 0xFFFF_FFFF
    return value


def fractional_bits(maximum: float, headroom_percent: int) -> int:
    allowed = SIGNED_MAX * (100 - headroom_percent) / 100
    return math.floor(math.log2(allowed / maximum))


def scaled(text: str, bits: int) -> int:
    return round(float(text) * (1 << bits))


def main() -> None:
    source = json.loads(SOURCE.read_text(encoding="utf-8"))
    envelopes = source["envelopes"]
    headroom = source["headroom_percent"]
    specs = [
        ("TIME", "time_s"),
        ("POSITION", "position_m"),
        ("VELOCITY", "velocity_mps"),
        ("ACCELERATION", "acceleration_mps2"),
        ("MASS", "mass_kg"),
        ("FORCE", "force_n"),
        ("MOMENT_ARM", "moment_arm_m"),
        ("INERTIA", "inertia_kgm2"),
        ("TORQUE", "torque_nm"),
        ("ANGULAR_RATE", "angular_rate_radps"),
        ("COEFFICIENT", "coefficient"),
        ("AREA", "area_m2"),
        ("STATIC_MARGIN", "static_margin_cal"),
        ("ANGLE", "angle_rad"),
        ("WIND", "wind_mps"),
    ]
    bits: dict[str, int] = {}
    maxima: dict[str, int] = {}
    for name, key in specs:
        bound = max(abs(float(value)) for value in envelopes[key])
        bits[name] = fractional_bits(bound, headroom)
        maxima[name] = scaled(str(bound), bits[name])
        assert maxima[name] <= SIGNED_MAX * 3 // 4

    lines = [
        "// Generated by phase8/reference/generate_numeric.py. Do not edit by hand.",
        f'pub const HOBBY_SPATIAL_NUMERIC_CONTRACT: &str = "{source["contract"]}";',
        f"pub const HOBBY_SPATIAL_NUMERIC_CONTRACT_ID: u32 = 0x{fnv1a32(source['contract']):08x};",
        f"pub const HOBBY_SPATIAL_ENVIRONMENT_ID: u32 = 0x{fnv1a32(source['environment']):08x};",
        "",
    ]
    for name, _ in specs:
        lines.append(f"pub const SPATIAL_{name}_FRACTIONAL_BITS: u8 = {bits[name]};")
    lines += ["", "pub const SPATIAL_QUATERNION_FRACTIONAL_BITS: u8 = 30;"]
    for key, value in source["cadence_seconds"].items():
        lines.append(f"pub const SPATIAL_{key.upper()}_STEP_RAW: i32 = {scaled(value, bits['TIME']):_};")
    lines.append("")
    for name, _ in specs:
        lines.append(f"pub const SPATIAL_MAX_{name}_RAW: i32 = {maxima[name]:_};")
    rendered = "\n".join(lines) + "\n"
    if "--check" in sys.argv:
        if OUTPUT.read_text(encoding="utf-8") != rendered:
            raise SystemExit(f"stale generated file: {OUTPUT}")
    else:
        OUTPUT.parent.mkdir(parents=True, exist_ok=True)
        OUTPUT.write_text(rendered, encoding="utf-8", newline="\n")


if __name__ == "__main__":
    main()
