//! Strict KSB11-to-KPS1 replay boundary.
//!
//! No client-visible frame is returned until the sealed archive has passed
//! structural validation, its action transcript has passed independent strict
//! decoding, and deterministic re-execution has regenerated byte-identical
//! KSB11 evidence.

use crate::global_display::{
    build_nominal_global_display_replay, GlobalDisplayPublishError,
    CURRENT_NOMINAL_REEXECUTION_EVIDENCE_ID,
};
use crate::phase11_authoring::{
    project_from_bundle, AuthoringError, CompiledMissionProject, MissionScenario,
};
use crate::phase11_session::{
    verify_complete_session, SessionBundleError, SessionBundleScan, SessionSegmentKind,
};
use crate::presentation_adapter::{FullMissionPresentationSession, PresentationSessionError};
use ksa64_interface::phase11::{
    parse_kal11_header, parse_kal11_record, ActionLogRecord, OperationalRole, UplinkControlKind,
    UplinkReasonCode, UplinkState, KAL11_HEADER_LENGTH, KAL11_RECORD_LENGTH,
};
use ksa64_presentation::{
    encode_typed_payload, write_kps1_frame, DispositionView, GlobalDisplayFrameId,
    GlobalDisplayPathLod, GlobalDisplayReplayEntryKind, GlobalDisplayReplayEntryV1,
    GlobalDisplaySampleV1, GlobalDisplaySourceId, Kps1Error, Kps1Header, PresentationActionIntent,
    PresentationActionOperation, PresentationCursors, PresentationLifecycle, PresentationPace,
    PresentationPayload, PresentationRole, PresentationSession, ProcedureView,
    SealedEvidenceMetadata, TransportStatusView, KPS1_CAPABILITY_GLOBAL_DISPLAY_V1,
    KPS1_FLAG_COALESCED, KPS1_FLAG_FINAL, KPS1_FLAG_LOSSY,
};

const REPLAY_BATCH_LIMIT: usize = 2_048;
const ACTION_CHAIN_INITIAL: u32 = 0x811c_9dc5;

/// Public, noncanonical information about a verified replay.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct VerifiedReplayMetadata {
    pub session_definition_identity: u32,
    pub action_identity: u32,
    pub completed_evidence_identity: u32,
    pub manifest_sha256: [u8; 32],
    pub role: PresentationRole,
    pub session_nonce: u64,
    pub frame_count: u64,
}

/// A complete role-filtered presentation replay.
///
/// Construction is deliberately eager. The API exposes KPS1 frames and safe
/// metadata only; it never exposes KSB11 segments, canonical telemetry, or
/// private world/flight structures.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct VerifiedPresentationReplay {
    metadata: VerifiedReplayMetadata,
    frames: Vec<Vec<u8>>,
}

impl VerifiedPresentationReplay {
    pub fn open(
        input: &[u8],
        role: PresentationRole,
        session_nonce: u64,
    ) -> Result<Self, PresentationReplayError> {
        Self::open_with_capabilities(input, role, session_nonce, 0)
    }

    pub fn open_with_capabilities(
        input: &[u8],
        role: PresentationRole,
        session_nonce: u64,
        capability_mask: u64,
    ) -> Result<Self, PresentationReplayError> {
        if session_nonce == 0 {
            return Err(PresentationReplayError::Kps1(Kps1Error::Session));
        }
        let scan = verify_complete_session(input).map_err(PresentationReplayError::Bundle)?;
        let manifest_sha256 = scan.manifest_sha256.ok_or(PresentationReplayError::Bundle(
            SessionBundleError::Manifest,
        ))?;
        let project = project_from_bundle(input).map_err(PresentationReplayError::Authoring)?;
        if project.scenario != MissionScenario::GnssLossFull {
            return Err(PresentationReplayError::Unsupported);
        }
        let actions = strict_action_log(&scan)?;
        let mut emitter = ReplayEmitter::new(
            role,
            session_nonce,
            capability_mask & KPS1_CAPABILITY_GLOBAL_DISPLAY_V1,
        )?;
        execute_verified_replay(input, project, &actions, &mut emitter)?;
        let metadata = VerifiedReplayMetadata {
            session_definition_identity: scan.identity.definition,
            action_identity: scan.identity.actions,
            completed_evidence_identity: scan.identity.completed_evidence,
            manifest_sha256,
            role,
            session_nonce,
            frame_count: emitter.frames.len() as u64,
        };
        Ok(Self {
            metadata,
            frames: emitter.frames,
        })
    }

    pub const fn metadata(&self) -> VerifiedReplayMetadata {
        self.metadata
    }

    pub fn kps1_frames(&self) -> &[Vec<u8>] {
        &self.frames
    }

    pub fn into_kps1_frames(self) -> Vec<Vec<u8>> {
        self.frames
    }

    /// Re-execute and validate the accepted Phase 10 nominal mission before
    /// exposing its noncanonical, role-filtered global display stream.
    /// This is read-only display evidence; it never fabricates a KSB11 bundle.
    pub fn open_nominal_global(
        role: PresentationRole,
        session_nonce: u64,
    ) -> Result<Self, PresentationReplayError> {
        if session_nonce == 0 {
            return Err(PresentationReplayError::Kps1(Kps1Error::Session));
        }
        let replay = build_nominal_global_display_replay()
            .map_err(PresentationReplayError::GlobalDisplay)?;
        let definition = replay.definition(role);
        let compatibility = replay.compatibility_audit();
        let mut emitter =
            ReplayEmitter::new(role, session_nonce, KPS1_CAPABILITY_GLOBAL_DISPLAY_V1)?;
        emitter.push(PresentationPayload::GlobalDisplayDefinition(definition), 0)?;
        for batch in replay.samples_after(0, role).chunks(128) {
            emitter.push(
                PresentationPayload::GlobalDisplaySampleBatch(batch.to_vec()),
                0,
            )?;
        }
        for transition in replay.transitions_after(0) {
            emitter.push(PresentationPayload::GlobalDisplayTransition(*transition), 0)?;
        }
        for source in [
            GlobalDisplaySourceId::Planned,
            GlobalDisplaySourceId::OnboardEstimate,
            GlobalDisplaySourceId::GroundEstimate,
            GlobalDisplaySourceId::SimTruth,
        ] {
            for frame in [
                GlobalDisplayFrameId::LocalEnu,
                GlobalDisplayFrameId::EarthFixedEcef,
                GlobalDisplayFrameId::EarthInertialGcrf,
            ] {
                for lod in [
                    GlobalDisplayPathLod::OneSecond,
                    GlobalDisplayPathLod::FourSecond,
                ] {
                    let mut chunk_index = 0_u16;
                    while let Ok(chunk) = replay.path_chunk(role, source, frame, lod, chunk_index) {
                        let chunk_count = chunk.chunk_count;
                        emitter.push(PresentationPayload::GlobalDisplayPathChunk(chunk), 0)?;
                        chunk_index = chunk_index.saturating_add(1);
                        if chunk_index >= chunk_count {
                            break;
                        }
                    }
                }
            }
        }
        emitter.push(
            PresentationPayload::GlobalReplayIndex(replay.replay_index()),
            0,
        )?;
        let metadata = VerifiedReplayMetadata {
            session_definition_identity: definition.display_identity,
            action_identity: compatibility.event_identity,
            completed_evidence_identity: CURRENT_NOMINAL_REEXECUTION_EVIDENCE_ID,
            manifest_sha256: compatibility.current_hashes.ktt10,
            role,
            session_nonce,
            frame_count: emitter.frames.len() as u64,
        };
        Ok(Self {
            metadata,
            frames: emitter.frames,
        })
    }
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub enum PresentationReplayError {
    Bundle(SessionBundleError),
    Authoring(AuthoringError),
    ActionLog,
    Unsupported,
    Authority(PresentationSessionError),
    Kps1(Kps1Error),
    CanonicalMismatch,
    GlobalDisplay(GlobalDisplayPublishError),
}

fn execute_verified_replay(
    expected_bundle: &[u8],
    project: CompiledMissionProject,
    actions: &[ActionLogRecord],
    emitter: &mut ReplayEmitter,
) -> Result<(), PresentationReplayError> {
    // The authority uses the canonical scripted role. ReplayEmitter separately
    // applies the immutable client role before any DTO is encoded.
    let mut session =
        FullMissionPresentationSession::compiled(project, OperationalRole::ScriptedOperator)
            .map_err(PresentationReplayError::Authority)?;
    session
        .prepare()
        .map_err(PresentationReplayError::Authority)?;
    session
        .set_pace(PresentationPace::Fast)
        .map_err(PresentationReplayError::Authority)?;
    emitter.capture(&session)?;

    let mut action_index = 0usize;
    let mut client_action_sequence = 1u64;
    while session.lifecycle() != PresentationLifecycle::Completed {
        let epoch = session.latest_snapshot().release_epoch;
        while actions
            .get(action_index)
            .is_some_and(|record| record.epoch == epoch)
        {
            apply_recorded_action(
                &mut session,
                actions[action_index],
                &mut client_action_sequence,
            )?;
            emitter.capture(&session)?;
            action_index += 1;
        }
        if actions
            .get(action_index)
            .is_some_and(|record| record.epoch < epoch)
        {
            return Err(PresentationReplayError::ActionLog);
        }
        session
            .advance_one_release()
            .map_err(PresentationReplayError::Authority)?;
        emitter.capture(&session)?;
    }
    if action_index != actions.len() {
        return Err(PresentationReplayError::ActionLog);
    }
    if session.sealed_evidence_bytes() != Some(expected_bundle) {
        return Err(PresentationReplayError::CanonicalMismatch);
    }
    emitter.finish(&session)
}

fn apply_recorded_action(
    session: &mut FullMissionPresentationSession,
    record: ActionLogRecord,
    client_action_sequence: &mut u64,
) -> Result<(), PresentationReplayError> {
    if record.reason != UplinkReasonCode::Accepted {
        return Err(PresentationReplayError::ActionLog);
    }
    let proposal = session
        .current_action_proposal()
        .ok_or(PresentationReplayError::ActionLog)?;
    if proposal.load_identity != record.load_identity {
        return Err(PresentationReplayError::ActionLog);
    }
    match (record.action_kind, record.state) {
        (UplinkControlKind::StageReceipt, UplinkState::Staged) => {
            submit_replay_intent(
                session,
                proposal.proposal_identity,
                0,
                proposal.activation_epoch,
                PresentationActionOperation::Review,
                client_action_sequence,
            )?;
            submit_replay_intent(
                session,
                proposal.proposal_identity,
                proposal.load_identity,
                proposal.activation_epoch,
                PresentationActionOperation::Stage,
                client_action_sequence,
            )
        }
        (UplinkControlKind::CommitReceipt, UplinkState::Committed) => submit_replay_intent(
            session,
            proposal.proposal_identity,
            proposal.load_identity,
            proposal.activation_epoch,
            PresentationActionOperation::Commit,
            client_action_sequence,
        ),
        (UplinkControlKind::Cancellation, UplinkState::Cancelled) => submit_replay_intent(
            session,
            proposal.proposal_identity,
            proposal.load_identity,
            proposal.activation_epoch,
            PresentationActionOperation::Cancel,
            client_action_sequence,
        ),
        _ => Err(PresentationReplayError::ActionLog),
    }
}

fn submit_replay_intent(
    session: &mut FullMissionPresentationSession,
    proposal_identity: u32,
    expected_load_identity: u32,
    activation_epoch: u32,
    operation: PresentationActionOperation,
    client_action_sequence: &mut u64,
) -> Result<(), PresentationReplayError> {
    session
        .submit_action(PresentationActionIntent {
            proposal_identity,
            expected_load_identity,
            operation,
            requested_activation_epoch: activation_epoch,
            client_action_sequence: *client_action_sequence,
        })
        .map_err(PresentationReplayError::Authority)?;
    *client_action_sequence = client_action_sequence
        .checked_add(1)
        .ok_or(PresentationReplayError::ActionLog)?;
    Ok(())
}

fn strict_action_log(
    scan: &SessionBundleScan,
) -> Result<Vec<ActionLogRecord>, PresentationReplayError> {
    let mut logs = scan
        .segments
        .iter()
        .filter(|segment| segment.kind == SessionSegmentKind::ActionLog);
    let segment = logs.next().ok_or(PresentationReplayError::ActionLog)?;
    if logs.next().is_some() || segment.payload.len() < KAL11_HEADER_LENGTH {
        return Err(PresentationReplayError::ActionLog);
    }
    let header = parse_kal11_header(&segment.payload[..KAL11_HEADER_LENGTH])
        .map_err(|_| PresentationReplayError::ActionLog)?;
    let count =
        usize::try_from(header.action_count).map_err(|_| PresentationReplayError::ActionLog)?;
    let expected_length = KAL11_HEADER_LENGTH
        .checked_add(
            count
                .checked_mul(KAL11_RECORD_LENGTH)
                .ok_or(PresentationReplayError::ActionLog)?,
        )
        .ok_or(PresentationReplayError::ActionLog)?;
    if segment.payload.len() != expected_length
        || !header.complete
        || header.session_definition_identity != scan.identity.definition
        || header.transcript_identity != scan.identity.actions
        || header.final_chain == 0
    {
        return Err(PresentationReplayError::ActionLog);
    }

    let mut records = Vec::with_capacity(count);
    let mut prior_chain = ACTION_CHAIN_INITIAL;
    for (index, bytes) in segment.payload[KAL11_HEADER_LENGTH..]
        .chunks_exact(KAL11_RECORD_LENGTH)
        .enumerate()
    {
        let record = parse_kal11_record(bytes).map_err(|_| PresentationReplayError::ActionLog)?;
        if record.sequence != index as u32 + 1
            || record.prior_chain != prior_chain
            || record.chain != action_record_chain(record)
        {
            return Err(PresentationReplayError::ActionLog);
        }
        prior_chain = record.chain;
        records.push(record);
    }
    if prior_chain != header.final_chain || prior_chain != scan.identity.actions {
        return Err(PresentationReplayError::ActionLog);
    }
    Ok(records)
}

fn action_record_chain(record: ActionLogRecord) -> u32 {
    hash_words(&[
        record.prior_chain,
        record.sequence,
        record.epoch,
        u32::from(record.procedure_step),
        record.action_kind as u32,
        record.state as u32,
        record.reason as u32,
        record.load_identity,
    ])
}

fn hash_words(values: &[u32]) -> u32 {
    let mut hash = ACTION_CHAIN_INITIAL;
    for value in values {
        for byte in value.to_le_bytes() {
            hash = (hash ^ u32::from(byte)).wrapping_mul(0x0100_0193);
        }
    }
    hash.max(1)
}

struct ReplayEmitter {
    role: PresentationRole,
    session_nonce: u64,
    next_frame_sequence: u64,
    cursors: PresentationCursors,
    last_snapshot_sequence: u64,
    last_procedure: Option<ProcedureView>,
    last_disposition: Option<DispositionView>,
    last_prediction_checksum: u32,
    last_transport: Option<TransportStatusView>,
    last_evidence: Option<SealedEvidenceMetadata>,
    capability_mask: u64,
    global_definition_sent: bool,
    global_sample_index: u32,
    global_transition_index: u32,
    pending_global_samples: Vec<GlobalDisplaySampleV1>,
    global_bookmarks: Vec<GlobalDisplayReplayEntryV1>,
    frames: Vec<Vec<u8>>,
}

impl ReplayEmitter {
    fn new(
        role: PresentationRole,
        session_nonce: u64,
        capability_mask: u64,
    ) -> Result<Self, PresentationReplayError> {
        if session_nonce == 0 {
            return Err(PresentationReplayError::Kps1(Kps1Error::Session));
        }
        Ok(Self {
            role,
            session_nonce,
            next_frame_sequence: 1,
            cursors: PresentationCursors::default(),
            last_snapshot_sequence: 0,
            last_procedure: None,
            last_disposition: None,
            last_prediction_checksum: 0,
            last_transport: None,
            last_evidence: None,
            capability_mask,
            global_definition_sent: false,
            global_sample_index: 0,
            global_transition_index: 0,
            pending_global_samples: Vec::new(),
            global_bookmarks: Vec::new(),
            frames: Vec::new(),
        })
    }

    fn capture(
        &mut self,
        session: &FullMissionPresentationSession,
    ) -> Result<(), PresentationReplayError> {
        self.capture_events(session)?;
        self.capture_timeline(session)?;
        self.capture_receipts(session)?;
        self.capture_samples(session)?;
        self.capture_global_display(session, false)?;

        let snapshot = session.latest_snapshot().filter_for_role(self.role);
        if snapshot.publication_sequence > self.last_snapshot_sequence {
            self.last_snapshot_sequence = snapshot.publication_sequence;
            self.push(
                PresentationPayload::Snapshot(snapshot.clone()),
                KPS1_FLAG_COALESCED,
            )?;
        }

        let mut procedure = session.current_procedure();
        if let Some(value) = procedure.as_mut() {
            value.hints_available = self.role == PresentationRole::GuidedOperator;
        }
        if procedure != self.last_procedure {
            if let Some(value) = procedure.clone() {
                self.push(PresentationPayload::Procedure(value), 0)?;
            }
            self.last_procedure = procedure;
        }

        let disposition = session.current_disposition();
        if disposition != self.last_disposition {
            if let Some(value) = disposition {
                self.push(PresentationPayload::Disposition(value), 0)?;
            }
            self.last_disposition = disposition;
        }

        if snapshot.prediction.prediction_checksum != 0
            && snapshot.prediction.prediction_checksum != self.last_prediction_checksum
        {
            self.last_prediction_checksum = snapshot.prediction.prediction_checksum;
            for path in session.current_prediction_paths() {
                self.push(PresentationPayload::PredictionPath(path), 0)?;
            }
        }

        let transport = session.transport_status();
        if self.last_transport != Some(transport) {
            self.push(PresentationPayload::TransportStatus(transport), 0)?;
            self.last_transport = Some(transport);
        }
        Ok(())
    }

    fn finish(
        &mut self,
        session: &FullMissionPresentationSession,
    ) -> Result<(), PresentationReplayError> {
        self.capture_global_display(session, true)?;
        let evidence = session
            .finalization_evidence()
            .ok_or(PresentationReplayError::CanonicalMismatch)?;
        if self.last_evidence != Some(evidence) {
            self.push(
                PresentationPayload::EvidenceMetadata(evidence),
                KPS1_FLAG_FINAL,
            )?;
            self.last_evidence = Some(evidence);
        }
        Ok(())
    }

    fn capture_global_display(
        &mut self,
        session: &FullMissionPresentationSession,
        finishing: bool,
    ) -> Result<(), PresentationReplayError> {
        if self.capability_mask & KPS1_CAPABILITY_GLOBAL_DISPLAY_V1 == 0 {
            return Ok(());
        }
        let authority = session.authority();
        if !self.global_definition_sent {
            let definition = authority
                .global_display_definition()
                .filter_for_role(self.role);
            self.push(PresentationPayload::GlobalDisplayDefinition(definition), 0)?;
            self.global_definition_sent = true;
        }
        let samples = authority.global_display_samples_after(self.global_sample_index);
        self.global_sample_index = self
            .global_sample_index
            .saturating_add(u32::try_from(samples.len()).unwrap_or(u32::MAX));
        self.pending_global_samples.extend(
            samples
                .into_iter()
                .map(|sample| sample.filter_for_role(self.role)),
        );
        while self.pending_global_samples.len() >= 128
            || (finishing && !self.pending_global_samples.is_empty())
        {
            let count = self.pending_global_samples.len().min(128);
            let batch = self.pending_global_samples.drain(..count).collect();
            self.push(PresentationPayload::GlobalDisplaySampleBatch(batch), 0)?;
        }
        let transitions = authority
            .global_display_transitions_after(self.global_transition_index)
            .to_vec();
        self.global_transition_index = self
            .global_transition_index
            .saturating_add(u32::try_from(transitions.len()).unwrap_or(u32::MAX));
        for transition in transitions {
            self.push(PresentationPayload::GlobalDisplayTransition(transition), 0)?;
        }
        if finishing {
            for source in [
                GlobalDisplaySourceId::Planned,
                GlobalDisplaySourceId::OnboardEstimate,
                GlobalDisplaySourceId::GroundEstimate,
                GlobalDisplaySourceId::SimTruth,
            ] {
                for frame in [
                    GlobalDisplayFrameId::LocalEnu,
                    GlobalDisplayFrameId::EarthFixedEcef,
                    GlobalDisplayFrameId::EarthInertialGcrf,
                ] {
                    for lod in [
                        GlobalDisplayPathLod::OneSecond,
                        GlobalDisplayPathLod::FourSecond,
                    ] {
                        let mut chunk_index = 0_u16;
                        while let Ok(chunk) =
                            authority.global_display_path_chunk(source, frame, lod, chunk_index)
                        {
                            let chunk_count = chunk.chunk_count;
                            self.push(PresentationPayload::GlobalDisplayPathChunk(chunk), 0)?;
                            chunk_index = chunk_index.saturating_add(1);
                            if chunk_index >= chunk_count {
                                break;
                            }
                        }
                    }
                }
            }
            let mut replay_index = authority.global_display_replay_index();
            replay_index
                .entries
                .extend(self.global_bookmarks.iter().copied());
            replay_index.entries.sort_by_key(|entry| {
                (
                    entry.release_epoch,
                    entry.mission_time_q16,
                    entry.kind as u8,
                    entry.event_identity,
                )
            });
            self.push(PresentationPayload::GlobalReplayIndex(replay_index), 0)?;
        }
        Ok(())
    }

    fn capture_events(
        &mut self,
        session: &FullMissionPresentationSession,
    ) -> Result<(), PresentationReplayError> {
        loop {
            let batch = session
                .read_events(self.cursors.events, REPLAY_BATCH_LIMIT)
                .map_err(|_| PresentationReplayError::ActionLog)?;
            self.cursors.events = batch.next_cursor;
            if batch.records.is_empty() {
                return Ok(());
            }
            self.push(
                PresentationPayload::EventBatch(
                    batch
                        .records
                        .into_iter()
                        .map(|record| record.value)
                        .collect(),
                ),
                0,
            )?;
        }
    }

    fn capture_timeline(
        &mut self,
        session: &FullMissionPresentationSession,
    ) -> Result<(), PresentationReplayError> {
        loop {
            let batch = session
                .read_timeline(self.cursors.timeline, REPLAY_BATCH_LIMIT)
                .map_err(|_| PresentationReplayError::ActionLog)?;
            self.cursors.timeline = batch.next_cursor;
            if batch.records.is_empty() {
                return Ok(());
            }
            for record in batch.records {
                if self.capability_mask & KPS1_CAPABILITY_GLOBAL_DISPLAY_V1 != 0
                    && matches!(record.value.event_identity, 0x12b4_1001 | 0x12b4_1002)
                {
                    self.global_bookmarks.push(GlobalDisplayReplayEntryV1 {
                        release_epoch: record.value.release_epoch,
                        mission_time_q16: record.value.release_epoch.saturating_mul(2_048),
                        kind: GlobalDisplayReplayEntryKind::Fault,
                        source_identity: record.value.source_identity,
                        event_identity: record.value.event_identity,
                        detail_identity: record.value.severity as u32,
                    });
                }
                self.push(PresentationPayload::TimelineEvent(record.value), 0)?;
            }
        }
    }

    fn capture_receipts(
        &mut self,
        session: &FullMissionPresentationSession,
    ) -> Result<(), PresentationReplayError> {
        loop {
            let batch = session
                .read_action_receipts(self.cursors.action_receipts, REPLAY_BATCH_LIMIT)
                .map_err(|_| PresentationReplayError::ActionLog)?;
            self.cursors.action_receipts = batch.next_cursor;
            if batch.records.is_empty() {
                return Ok(());
            }
            for record in batch.records {
                if self.capability_mask & KPS1_CAPABILITY_GLOBAL_DISPLAY_V1 != 0 {
                    self.global_bookmarks.push(GlobalDisplayReplayEntryV1 {
                        release_epoch: record.value.receipt_epoch,
                        mission_time_q16: record.value.receipt_epoch.saturating_mul(2_048),
                        kind: GlobalDisplayReplayEntryKind::ProcedureAction,
                        source_identity: record.value.operation as u32,
                        event_identity: record
                            .value
                            .load_identity
                            .max(record.value.proposal_identity),
                        detail_identity: record.value.receipt_checksum,
                    });
                }
                self.push(PresentationPayload::ActionReceipt(record.value), 0)?;
            }
        }
    }

    fn capture_samples(
        &mut self,
        session: &FullMissionPresentationSession,
    ) -> Result<(), PresentationReplayError> {
        loop {
            let batch = session
                .read_release_samples(self.cursors.release_samples, REPLAY_BATCH_LIMIT)
                .map_err(|_| PresentationReplayError::ActionLog)?;
            self.cursors.release_samples = batch.next_cursor;
            if batch.records.is_empty() {
                return Ok(());
            }
            self.push(
                PresentationPayload::ReleaseSampleBatch(
                    batch
                        .records
                        .into_iter()
                        .map(|record| record.value)
                        .collect(),
                ),
                KPS1_FLAG_LOSSY,
            )?;
        }
    }

    fn push(
        &mut self,
        value: PresentationPayload,
        flags: u32,
    ) -> Result<(), PresentationReplayError> {
        let payload =
            encode_typed_payload(&value, self.role).map_err(PresentationReplayError::Kps1)?;
        let header = Kps1Header {
            kind: value.kind(),
            flags,
            session_nonce: self.session_nonce,
            sequence: self.next_frame_sequence,
            correlation_id: 0,
            payload_length: payload.len() as u32,
        };
        let length = header
            .encoded_length()
            .ok_or(PresentationReplayError::Kps1(Kps1Error::Length))?;
        let mut frame = vec![0; length];
        write_kps1_frame(header, &payload, &mut frame).map_err(PresentationReplayError::Kps1)?;
        self.frames.push(frame);
        self.next_frame_sequence = self
            .next_frame_sequence
            .checked_add(1)
            .ok_or(PresentationReplayError::Kps1(Kps1Error::Sequence))?;
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::phase11_authoring::{compile_project_source, complete_project_session};
    use crate::phase11_session::{SessionBundleBuilder, SessionBundleIdentity, SessionSegment};
    use crate::phase12b_live::FULL_GNSS_LOSS_SOURCE;
    use ksa64_interface::phase11::{write_kal11_header, write_kal11_record, ActionLogHeader};
    use ksa64_presentation::{
        decode_typed_payload, parse_kps1_frame, NavigationView, OperationalSnapshot,
        PredictionSummaryView, PresentationMessageKind, SimTruthView, SNAPSHOT_VALID_TRUTH,
    };

    fn action_record(sequence: u32, prior_chain: u32) -> ActionLogRecord {
        let mut value = ActionLogRecord {
            sequence,
            epoch: 100 + sequence,
            role: OperationalRole::FlightController,
            action_kind: UplinkControlKind::StageReceipt,
            state: UplinkState::Staged,
            reason: UplinkReasonCode::Accepted,
            load_identity: 0x1100_0000 + sequence,
            detail_identity: 0x2200_0000 + sequence,
            procedure_step: sequence as u16,
            arguments: [0; 4],
            prior_chain,
            chain: 0,
        };
        value.chain = action_record_chain(value);
        value
    }

    fn action_log(definition: u32, transcript: u32) -> Vec<u8> {
        let first = action_record(1, ACTION_CHAIN_INITIAL);
        let mut bytes = vec![0; KAL11_HEADER_LENGTH + KAL11_RECORD_LENGTH];
        write_kal11_header(
            &ActionLogHeader {
                session_definition_identity: definition,
                transcript_identity: transcript,
                package_manifest_identity: 3,
                plan_identity: 4,
                action_count: 1,
                final_chain: first.chain,
                complete: true,
            },
            &mut bytes[..KAL11_HEADER_LENGTH],
        )
        .unwrap();
        write_kal11_record(&first, &mut bytes[KAL11_HEADER_LENGTH..]).unwrap();
        bytes
    }

    #[test]
    fn action_log_requires_exact_identity_sequence_and_chain() {
        let first = action_record(1, ACTION_CHAIN_INITIAL);
        let identity = crate::phase11_session::SessionBundleIdentity {
            definition: 1,
            actions: first.chain,
            completed_evidence: 3,
        };
        let mut scan = SessionBundleScan {
            identity,
            segments: vec![SessionSegment {
                kind: SessionSegmentKind::ActionLog,
                payload: action_log(identity.definition, identity.actions),
            }],
            valid_length: 0,
            manifest_sha256: Some([1; 32]),
            sealed: true,
            completed: true,
        };
        assert_eq!(strict_action_log(&scan), Ok(vec![first]));
        scan.segments[0].payload[KAL11_HEADER_LENGTH + 40] ^= 1;
        assert_eq!(
            strict_action_log(&scan),
            Err(PresentationReplayError::ActionLog)
        );
    }

    #[test]
    fn corrupt_ksb11_fails_before_project_or_presentation_decode() {
        let identity = SessionBundleIdentity {
            definition: 1,
            actions: 2,
            completed_evidence: 3,
        };
        let mut builder = SessionBundleBuilder::new(identity).unwrap();
        builder
            .push(SessionSegmentKind::SourceLedger, b"{}".to_vec())
            .unwrap();
        builder
            .push(
                SessionSegmentKind::ActionLog,
                action_log(identity.definition, identity.actions),
            )
            .unwrap();
        builder
            .push(SessionSegmentKind::Debrief, b"debrief".to_vec())
            .unwrap();
        let mut bytes = builder.encode().unwrap();
        bytes[crate::phase11_session::KSB11_HEADER_LENGTH] ^= 1;
        assert_eq!(
            VerifiedPresentationReplay::open(&bytes, PresentationRole::Observer, 0x1234),
            Err(PresentationReplayError::Bundle(
                SessionBundleError::Checksum
            ))
        );
    }

    #[test]
    fn replay_emitter_reapplies_role_filter_before_encoding() {
        let mut emitter = ReplayEmitter::new(PresentationRole::Observer, 7, 0).unwrap();
        let snapshot = OperationalSnapshot {
            presentation_model_identity: 1,
            session_definition_identity: 2,
            publication_sequence: 1,
            validity_mask: SNAPSHOT_VALID_TRUTH,
            role: PresentationRole::SimDirector,
            lifecycle: PresentationLifecycle::Completed,
            pace: PresentationPace::Fast,
            release_epoch: 1,
            release_period_micros: 31_250,
            frame_identity: 1,
            mission_time_q16: 1,
            onboard: NavigationView::default(),
            ground: NavigationView::default(),
            prediction: PredictionSummaryView::default(),
            flight_checksum: 1,
            command_checksum: 1,
            procedure_chain: 1,
            journal_chain: 1,
            action_chain: 1,
            staged_load_identity: 0,
            action_count: 0,
            rejected_loads: 0,
            gnss_state: 1,
            safe: false,
            truth: Some(SimTruthView::default()),
        }
        .filter_for_role(PresentationRole::Observer);
        emitter
            .push(PresentationPayload::Snapshot(snapshot), 0)
            .unwrap();
        let decoded = parse_kps1_frame(&emitter.frames[0]).unwrap();
        let payload = decode_typed_payload(
            decoded.header.kind,
            decoded.payload,
            PresentationRole::Observer,
        )
        .unwrap();
        let PresentationPayload::Snapshot(value) = payload else {
            panic!("expected snapshot");
        };
        assert_eq!(value.truth, None);
        assert_eq!(value.validity_mask & SNAPSHOT_VALID_TRUTH, 0);
    }

    #[test]
    fn invalid_nonce_fails_without_authority_work() {
        assert_eq!(
            VerifiedPresentationReplay::open(&[], PresentationRole::Observer, 0),
            Err(PresentationReplayError::Kps1(Kps1Error::Session))
        );
    }

    #[test]
    #[ignore = "two complete 21,591-release runs: fixture creation plus strict replay"]
    fn accepted_ksb11_replays_as_sequential_truth_filtered_kps1() {
        let project = compile_project_source(FULL_GNSS_LOSS_SOURCE).unwrap();
        let completed = complete_project_session(&project, true).unwrap();
        assert_eq!(completed.bundle.len(), 2_911_464);
        assert_eq!(
            crate::phase11_session::sha256(&completed.bundle),
            [
                0x75, 0x54, 0x11, 0x1f, 0x28, 0xd8, 0xf3, 0x62, 0x8a, 0xe3, 0xca, 0x9d, 0x06, 0x9f,
                0xad, 0x34, 0x20, 0x4e, 0x12, 0xf8, 0x62, 0x52, 0xef, 0xd0, 0x0e, 0xcf, 0x74, 0x4c,
                0x0e, 0xe0, 0xfc, 0xd4,
            ]
        );
        let replay = VerifiedPresentationReplay::open_with_capabilities(
            &completed.bundle,
            PresentationRole::Observer,
            0x1234_5678_9abc_def0,
            KPS1_CAPABILITY_GLOBAL_DISPLAY_V1,
        )
        .unwrap();
        assert_eq!(
            replay.metadata().frame_count,
            replay.kps1_frames().len() as u64
        );
        assert_eq!(
            replay.metadata().completed_evidence_identity,
            completed.evidence.evidence_identity
        );

        let mut expected_sequence = 1u64;
        let mut snapshots = 0usize;
        let mut global_samples = 0usize;
        let mut global_definition = false;
        let mut global_index = false;
        for frame in replay.kps1_frames() {
            let decoded = parse_kps1_frame(frame).unwrap();
            assert_eq!(decoded.header.sequence, expected_sequence);
            expected_sequence += 1;
            let payload = decode_typed_payload(
                decoded.header.kind,
                decoded.payload,
                PresentationRole::Observer,
            )
            .unwrap();
            match payload {
                PresentationPayload::Snapshot(value) => {
                    snapshots += 1;
                    assert_eq!(value.truth, None);
                    assert_eq!(value.validity_mask & SNAPSHOT_VALID_TRUTH, 0);
                }
                PresentationPayload::GlobalDisplayDefinition(value) => {
                    global_definition = true;
                    assert_eq!(
                        value.available_source_mask
                            & (1 << (GlobalDisplaySourceId::SimTruth as u8 - 1)),
                        0
                    );
                }
                PresentationPayload::GlobalDisplaySampleBatch(values) => {
                    global_samples += values.len();
                    assert!(values.iter().all(|value| value
                        .sources
                        .iter()
                        .all(|pose| pose.source != GlobalDisplaySourceId::SimTruth)));
                }
                PresentationPayload::GlobalReplayIndex(value) => {
                    global_index = true;
                    assert_eq!(value.last_release, 21_590);
                    assert!(value.entries.iter().any(|entry| {
                        entry.kind == GlobalDisplayReplayEntryKind::ProcedureAction
                    }));
                    assert!(value
                        .entries
                        .iter()
                        .any(|entry| entry.kind == GlobalDisplayReplayEntryKind::Fault));
                }
                _ => {}
            }
        }
        assert!(snapshots >= 21_592);
        assert!(global_definition);
        assert!(global_index);
        assert_eq!(global_samples, 21_591);
        let last = parse_kps1_frame(replay.kps1_frames().last().unwrap()).unwrap();
        assert_eq!(last.header.kind, PresentationMessageKind::EvidenceMetadata);
        assert_ne!(last.header.flags & KPS1_FLAG_FINAL, 0);
    }
}
