#!/usr/bin/env python3
"""Generate the Phase 7 250 m atmosphere and gravity tables."""

from __future__ import annotations

import math
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
OUTPUT = ROOT / "phase7" / "generated" / "environment_v1.rs"
STEP_M = 250
ATMOSPHERE_TOP_M = 86_000
GRAVITY_TOP_M = 150_000
EARTH_RADIUS_M = 6_371_000.0
G0 = 9.80665
R_AIR = 287.05287
GAMMA = 1.4

# 1976 U.S. Standard Atmosphere geopotential layers through 84.852 km.
LAYER_BASES_M = [0.0, 11_000.0, 20_000.0, 32_000.0, 47_000.0, 51_000.0, 71_000.0, 84_852.0]
LAPSE_KPM = [-0.0065, 0.0, 0.001, 0.0028, 0.0, -0.0028, -0.002, 0.0]


def layer_bases() -> tuple[list[float], list[float]]:
    temperatures = [288.15]
    pressures = [101_325.0]
    for index in range(len(LAYER_BASES_M) - 1):
        h0 = LAYER_BASES_M[index]
        h1 = LAYER_BASES_M[index + 1]
        t0 = temperatures[-1]
        p0 = pressures[-1]
        lapse = LAPSE_KPM[index]
        t1 = t0 + lapse * (h1 - h0)
        if lapse == 0.0:
            p1 = p0 * math.exp(-G0 * (h1 - h0) / (R_AIR * t0))
        else:
            p1 = p0 * (t0 / t1) ** (G0 / (R_AIR * lapse))
        temperatures.append(t1)
        pressures.append(p1)
    return temperatures, pressures


BASE_T, BASE_P = layer_bases()


def atmosphere(geometric_m: float) -> tuple[float, float]:
    # The standard uses geopotential altitude.
    h = EARTH_RADIUS_M * geometric_m / (EARTH_RADIUS_M + geometric_m)
    index = len(LAYER_BASES_M) - 1
    for candidate in range(len(LAYER_BASES_M) - 1):
        if h < LAYER_BASES_M[candidate + 1]:
            index = candidate
            break
    h0 = LAYER_BASES_M[index]
    t0 = BASE_T[index]
    p0 = BASE_P[index]
    lapse = LAPSE_KPM[index]
    temperature = t0 + lapse * (h - h0)
    if lapse == 0.0:
        pressure = p0 * math.exp(-G0 * (h - h0) / (R_AIR * t0))
    else:
        pressure = p0 * (t0 / temperature) ** (G0 / (R_AIR * lapse))
    density = pressure / (R_AIR * temperature)
    sound_speed = math.sqrt(GAMMA * R_AIR * temperature)
    return density, sound_speed


def render_array(name: str, values: list[int]) -> list[str]:
    lines = [f"pub static {name}: [i32; {len(values)}] = ["]
    for offset in range(0, len(values), 8):
        lines.append("    " + ", ".join(f"{value:_}" for value in values[offset : offset + 8]) + ",")
    lines.append("];")
    return lines


def main() -> None:
    density: list[int] = []
    sound_speed: list[int] = []
    for altitude in range(0, ATMOSPHERE_TOP_M + 1, STEP_M):
        rho, speed = atmosphere(float(altitude))
        density.append(round(rho * (1 << 29)))
        sound_speed.append(round(speed * (1 << 19)))
    gravity = [
        round(G0 * (EARTH_RADIUS_M / (EARTH_RADIUS_M + altitude)) ** 2 * (1 << 19))
        for altitude in range(0, GRAVITY_TOP_M + 1, STEP_M)
    ]
    lines = [
        "// Generated by phase7/reference/generate_environment.py. Do not edit by hand.",
        f"pub const HOBBY_ENVIRONMENT_STEP_M: i32 = {STEP_M};",
        f"pub const HOBBY_ATMOSPHERE_TOP_M: i32 = {ATMOSPHERE_TOP_M};",
        f"pub const HOBBY_GRAVITY_TOP_M: i32 = {GRAVITY_TOP_M};",
        "",
        *render_array("HOBBY_DENSITY_Q29", density),
        "",
        *render_array("HOBBY_SOUND_SPEED_Q19", sound_speed),
        "",
        *render_array("HOBBY_GRAVITY_Q19", gravity),
    ]
    rendered = "\n".join(lines) + "\n"
    if "--check" in sys.argv:
        if OUTPUT.read_text(encoding="utf-8") != rendered:
            raise SystemExit(f"stale generated file: {OUTPUT}")
    else:
        OUTPUT.write_text(rendered, encoding="utf-8", newline="\n")


if __name__ == "__main__":
    main()
