#!/usr/bin/env python3
"""Generate and verify the Phase 7 fixed-point numeric contract."""

from __future__ import annotations

import json
import math
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT / "phase7" / "numeric-contract.json"
OUTPUT = ROOT / "phase7" / "generated" / "numeric_v1.rs"
SIGNED_MAX = 2**31 - 1


def fnv1a32(text: str) -> int:
    value = 2_166_136_261
    for byte in text.encode("ascii"):
        value = ((value ^ byte) * 16_777_619) & 0xFFFF_FFFF
    return value


def fractional_bits(maximum: float, headroom_percent: int) -> int:
    allowed = SIGNED_MAX * (100 - headroom_percent) / 100
    return math.floor(math.log2(allowed / maximum))


def scaled(text: str, bits: int) -> int:
    return round(float(text) * (1 << bits))


def main() -> None:
    source = json.loads(SOURCE.read_text(encoding="utf-8"))
    envelopes = source["envelopes"]
    headroom = source["headroom_percent"]
    specs = [
        ("TIME", "time_s"),
        ("ALTITUDE", "altitude_m"),
        ("VELOCITY", "velocity_mps"),
        ("ACCELERATION", "acceleration_mps2"),
        ("MASS", "mass_kg"),
        ("FORCE", "force_n"),
        ("MASS_FLOW", "mass_flow_kgps"),
        ("DYNAMIC_PRESSURE", "dynamic_pressure_pa"),
        ("DENSITY", "density_kgpm3"),
        ("AREA", "reference_area_m2"),
        ("RECOVERY_CDA", "recovery_cda_m2"),
        ("MACH", "mach"),
    ]
    bits: dict[str, int] = {}
    maxima: dict[str, int] = {}
    for name, key in specs:
        bound = max(abs(float(value)) for value in envelopes[key])
        bits[name] = fractional_bits(bound, headroom)
        maxima[name] = scaled(str(bound), bits[name])
        assert maxima[name] <= SIGNED_MAX * 3 // 4

    lines = [
        "// Generated by phase7/reference/generate_numeric.py. Do not edit by hand.",
        f'pub const HOBBY_NUMERIC_CONTRACT: &str = "{source["contract"]}";',
        f"pub const HOBBY_NUMERIC_CONTRACT_ID: u32 = 0x{fnv1a32(source['contract']):08x};",
        f"pub const HOBBY_ENVIRONMENT_ID: u32 = 0x{fnv1a32('ksa64.environment.us76-250m-v1'):08x};",
        "",
    ]
    for name, _ in specs:
        lines.append(f"pub const HOBBY_{name}_FRACTIONAL_BITS: u8 = {bits[name]};")
    lines += [
        "",
        f"pub const HOBBY_POWERED_STEP_RAW: i32 = {scaled(source['cadence_seconds']['constrained_or_powered'], bits['TIME']):_};",
        f"pub const HOBBY_COAST_STEP_RAW: i32 = {scaled(source['cadence_seconds']['coast'], bits['TIME']):_};",
        f"pub const HOBBY_RECOVERY_STEP_RAW: i32 = {scaled(source['cadence_seconds']['recovery'], bits['TIME']):_};",
        "",
        f"pub const HOBBY_MAX_TIME_RAW: i32 = {maxima['TIME']:_};",
        f"pub const HOBBY_MIN_ALTITUDE_RAW: i32 = {scaled(envelopes['altitude_m'][0], bits['ALTITUDE']):_};",
        f"pub const HOBBY_MAX_ALTITUDE_RAW: i32 = {maxima['ALTITUDE']:_};",
    ]
    for name, _ in specs[2:]:
        lines.append(f"pub const HOBBY_MAX_{name}_RAW: i32 = {maxima[name]:_};")
    rendered = "\n".join(lines) + "\n"
    if "--check" in __import__("sys").argv:
        if OUTPUT.read_text(encoding="utf-8") != rendered:
            raise SystemExit(f"stale generated file: {OUTPUT}")
    else:
        OUTPUT.write_text(rendered, encoding="utf-8", newline="\n")


if __name__ == "__main__":
    main()
