#!/usr/bin/env python3
"""Independent float64 KSA-5A one-orbit Phase 10 coast reference."""

from __future__ import annotations

import argparse
import hashlib
import json
import math
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
OUT_JSON = ROOT / "phase10" / "generated" / "ksa5-coast-reference-v1.json"
OUT_RS = ROOT / "phase10" / "generated" / "ksa5_coast_reference_v1.rs"

POSITION_Q12 = (21_468_577, 3_871_182, 15_698_368)
VELOCITY_Q24 = (-66_327_286, 89_767_125, 68_337_641)
PHASE5_SUMMARY_CHECKSUM = 557_491_580
DURATION_SECONDS = 5_350.0
STEP_SECONDS = 1.0 / 32.0
MU = 398_600.4418
J2 = 1.08262668e-3
EARTH_RADIUS_KM = 6_378.137


def norm(vector: list[float]) -> float:
    return math.sqrt(sum(component * component for component in vector))


def gravity(position: list[float]) -> list[float]:
    radius = norm(position)
    z_ratio = position[2] / radius
    factor = 1.5 * J2 * (EARTH_RADIUS_KM / radius) ** 2
    common = -MU / radius**3
    return [
        common * position[0] * (1.0 - factor * (5.0 * z_ratio**2 - 1.0)),
        common * position[1] * (1.0 - factor * (5.0 * z_ratio**2 - 1.0)),
        common * position[2] * (1.0 - factor * (5.0 * z_ratio**2 - 3.0)),
    ]


def run() -> dict:
    position = [value / 4096.0 for value in POSITION_Q12]
    velocity = [value / 16_777_216.0 for value in VELOCITY_Q24]
    minimum_altitude = float("inf")
    maximum_altitude = float("-inf")
    steps = int(DURATION_SECONDS / STEP_SECONDS)
    for _ in range(steps):
        first = gravity(position)
        midpoint_velocity = [
            velocity[axis] + first[axis] * STEP_SECONDS * 0.5 for axis in range(3)
        ]
        midpoint_position = [
            position[axis] + velocity[axis] * STEP_SECONDS * 0.5 for axis in range(3)
        ]
        second = gravity(midpoint_position)
        position = [
            position[axis] + midpoint_velocity[axis] * STEP_SECONDS for axis in range(3)
        ]
        velocity = [
            velocity[axis] + second[axis] * STEP_SECONDS for axis in range(3)
        ]
        altitude = norm(position) - EARTH_RADIUS_KM
        minimum_altitude = min(minimum_altitude, altitude)
        maximum_altitude = max(maximum_altitude, altitude)
    payload = {
        "schema": "ksa64.phase10.ksa5-coast-reference-v1",
        "model": "independent-float64-central-j2-rk2",
        "phase5_summary_checksum": f"0x{PHASE5_SUMMARY_CHECKSUM:08x}",
        "duration_s": DURATION_SECONDS,
        "step_s": STEP_SECONDS,
        "steps": steps,
        "initial": {
            "position_q12_km": list(POSITION_Q12),
            "velocity_q24_km_s": list(VELOCITY_Q24),
        },
        "terminal": {
            "position_km": position,
            "velocity_km_s": velocity,
            "position_q12_km": [round(value * 4096.0) for value in position],
            "velocity_q24_km_s": [round(value * 16_777_216.0) for value in velocity],
        },
        "minimum_altitude_km": minimum_altitude,
        "maximum_altitude_km": maximum_altitude,
        "acceptance": {
            "position_delta_km": 5.0,
            "velocity_delta_m_s": 5.0,
        },
        "external_fixture_policy": {
            "satkit": "preferred frozen secondary reference",
            "gmat": "optional bounded orbital corroboration",
            "live_dependency_in_tests": False,
        },
    }
    canonical = json.dumps(payload, sort_keys=True, separators=(",", ":")).encode()
    payload["evidence_sha256"] = hashlib.sha256(canonical).hexdigest()
    return payload


def rust_fixture(payload: dict) -> str:
    terminal = payload["terminal"]
    return (
        "// Generated by phase10/reference/analyze_ksa5_coast.py.\n"
        f"pub const KSA5_FLOAT64_POSITION_Q12: [i32; 3] = {terminal['position_q12_km']!r};\n"
        f"pub const KSA5_FLOAT64_VELOCITY_Q24: [i32; 3] = {terminal['velocity_q24_km_s']!r};\n"
        f"pub const KSA5_FLOAT64_MIN_ALTITUDE_Q12: i32 = {round(payload['minimum_altitude_km'] * 4096)};\n"
        f"pub const KSA5_FLOAT64_MAX_ALTITUDE_Q12: i32 = {round(payload['maximum_altitude_km'] * 4096)};\n"
    ).replace("[", "[").replace("]", "]")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    payload = run()
    expected_json = json.dumps(payload, indent=2) + "\n"
    expected_rs = rust_fixture(payload)
    if args.check:
        if (
            not OUT_JSON.exists()
            or OUT_JSON.read_text() != expected_json
            or not OUT_RS.exists()
            or OUT_RS.read_text() != expected_rs
        ):
            raise SystemExit("phase10 KSA-5A coast evidence: stale")
        print("phase10 KSA-5A coast evidence: PASS")
        return
    OUT_JSON.write_text(expected_json)
    OUT_RS.write_text(expected_rs)
    print("phase10 KSA-5A coast evidence: generated")


if __name__ == "__main__":
    main()
