#!/usr/bin/env python3
"""Generate Phase 5 spatial-world lookup data and independent reference states."""
from __future__ import annotations

import argparse
import hashlib
import json
import math
from decimal import Decimal, ROUND_HALF_UP
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
JSON_OUT = ROOT / "phase5" / "generated" / "spatial-world-v1.json"
RUST_OUT = ROOT / "phase5" / "generated" / "spatial_world_tables_v1.rs"
EARTH_RADIUS = Decimal("6378.137")
MU = Decimal("398600.4418")


def raw(value: Decimal | str, bits: int) -> int:
    return int((Decimal(value) * (1 << bits)).to_integral_value(rounding=ROUND_HALF_UP))


def build() -> dict:
    acos = [round(math.acos(i / 256.0) / (2 * math.pi) * 65536) for i in range(257)]
    latitude = math.radians(28.5)
    launch_position = [
        raw(EARTH_RADIUS * Decimal(str(math.cos(latitude))), 12),
        0,
        raw(EARTH_RADIUS * Decimal(str(math.sin(latitude))), 12),
    ]
    omega = Decimal("0.00007292115")
    launch_velocity = [0, raw(omega * (Decimal(launch_position[0]) / (1 << 12)), 24), 0]
    radius = EARTH_RADIUS + Decimal(200)
    speed = (MU / radius).sqrt()
    inclination = math.radians(51.6)
    circular_position = [raw(radius, 12), 0, 0]
    circular_velocity = [
        0,
        raw(speed * Decimal(str(math.cos(inclination))), 24),
        raw(speed * Decimal(str(math.sin(inclination))), 24),
    ]
    return {
        "contract": "ksa64.spatial-world.phase5-v1",
        "portable_signature": "0x650d5aa7",
        "acos_turn16": acos,
        "launch_position_q12": launch_position,
        "launch_corotation_velocity_q24": launch_velocity,
        "circular_200km_51_6_position_q12": circular_position,
        "circular_200km_51_6_velocity_q24": circular_velocity,
    }


def rust(data: dict) -> str:
    def arr(values: list[int]) -> str:
        return "[" + ", ".join(str(v) for v in values) + "]"
    return f"""// Generated by phase5/reference/generate_spatial_world.py.
// Do not edit by hand.

pub const WORLD_SIGNATURE: u32 = 0x650d5aa7;
pub const ACOS_TURN16: [u16; 257] = {arr(data['acos_turn16'])};
pub const LAUNCH_POSITION_Q12: [i32; 3] = {arr(data['launch_position_q12'])};
pub const LAUNCH_COROTATION_VELOCITY_Q24: [i32; 3] = {arr(data['launch_corotation_velocity_q24'])};
pub const CIRCULAR_POSITION_Q12: [i32; 3] = {arr(data['circular_200km_51_6_position_q12'])};
pub const CIRCULAR_VELOCITY_Q24: [i32; 3] = {arr(data['circular_200km_51_6_velocity_q24'])};
"""


def write_or_check(path: Path, payload: bytes, check: bool) -> None:
    if check:
        if not path.exists() or path.read_bytes() != payload:
            raise SystemExit(f"stale generated artifact: {path.relative_to(ROOT)}")
        return
    path.write_bytes(payload)
    digest = hashlib.sha256(payload).hexdigest()
    path.with_suffix(path.suffix + ".sha256").write_text(f"{digest}  {path.name}\n", encoding="ascii")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    data = build()
    write_or_check(JSON_OUT, (json.dumps(data, indent=2) + "\n").encode(), args.check)
    write_or_check(RUST_OUT, rust(data).encode(), args.check)


if __name__ == "__main__":
    main()