#!/usr/bin/env python3
"""Generate and check the independent Phase 5 numeric/source contract."""
from __future__ import annotations
import argparse, hashlib, json, math, sys
from decimal import Decimal, ROUND_HALF_UP, getcontext
from pathlib import Path
getcontext().prec = 80
CONTRACT = "ksa64.numeric.phase5-v1"
ENVIRONMENT = "earth.eci-rotating-spherical-flex.v1"
SCENARIO = "ksa64.phase5.ksa5a-200km-51.6.v1"
BASE_KSC2_CRC = 0x5D362512

def fnv1a(text: str) -> int:
    h=2166136261
    for b in text.encode(): h=((h^b)*16777619)&0xffffffff
    return h

def raw(value: str, bits: int) -> int:
    return int((Decimal(value)*(1<<bits)).to_integral_value(rounding=ROUND_HALF_UP))

def turn32(degrees: str) -> int:
    return int((Decimal(degrees)/Decimal(360)*(1<<32)).to_integral_value(rounding=ROUND_HALF_UP)) & 0xffffffff

def formats():
    return {
      "position": {"storage":"i32","unit":"km","fractional_bits":12,"minimum":"-8379","maximum":"8379"},
      "velocity": {"storage":"i32","unit":"km/s","fractional_bits":24,"minimum":"-16","maximum":"16"},
      "acceleration": {"storage":"i32","unit":"km/s^2","fractional_bits":28,"minimum":"-0.2","maximum":"0.2"},
      "quaternion": {"storage":"i32","unit":"dimensionless","fractional_bits":30,"minimum":"-1","maximum":"1"},
      "angular_rate": {"storage":"i32","unit":"rad/s","fractional_bits":24,"minimum":"-8","maximum":"8"},
      "angular_acceleration": {"storage":"i32","unit":"rad/s^2","fractional_bits":24,"minimum":"-64","maximum":"64"},
      "inertia": {"storage":"i32","unit":"t*m^2","fractional_bits":12,"minimum":"0","maximum":"500000"},
      "torque": {"storage":"i32","unit":"MN*m","fractional_bits":16,"minimum":"-1000","maximum":"1000"},
      "geometry": {"storage":"i32","unit":"m","fractional_bits":16,"minimum":"-128","maximum":"128"},
      "modal_state": {"storage":"i32","unit":"rad or m","fractional_bits":24,"minimum":"-8","maximum":"8"},
      "frequency": {"storage":"i32","unit":"rad/s","fractional_bits":16,"minimum":"0","maximum":"64"},
      "damping": {"storage":"i32","unit":"dimensionless","fractional_bits":16,"minimum":"0","maximum":"1"}
    }

def contract(source):
    fs=formats()
    for spec in fs.values():
        bits=spec["fractional_bits"]; spec["raw_minimum"]=raw(spec["minimum"],bits); spec["raw_maximum"]=raw(spec["maximum"],bits)
    products=[
      ("quaternion product","quaternion","quaternion"),
      ("position velocity cross","position","velocity"),
      ("inertia angular rate","inertia","angular_rate"),
      ("angular momentum rate cross","angular_rate","inertia"),
      ("torque lever coupling","torque","geometry"),
      ("modal frequency state","frequency","modal_state")]
    widened=[]
    for name,a,b in products:
        av=max(abs(fs[a]["raw_minimum"]),abs(fs[a]["raw_maximum"])); bv=max(abs(fs[b]["raw_minimum"]),abs(fs[b]["raw_maximum"])); p=av*bv
        widened.append({"name":name,"operands":[a,b],"maximum_raw_product":p,"required_bits_including_sign":p.bit_length()+1})
    return {
      "contract":CONTRACT,"contract_id":fnv1a(CONTRACT),"environment":ENVIRONMENT,
      "environment_id":fnv1a(ENVIRONMENT),"scenario":SCENARIO,"scenario_id":fnv1a(SCENARIO),
      "base_ksc2_crc32":BASE_KSC2_CRC,"frames":{
        "eci":"right-handed; +Z north; +X longitude zero at epoch; +Y completes",
        "body":"+X nose; +Y vehicle right; +Z completes",
        "quaternion":"scalar-first Hamilton body-to-ECI active rotation",
        "local_guidance":"up/east/north"
      },
      "cadence":{"mission_step_s":"0.125","attitude_substeps":4,"fast_step_s":"0.03125"},
      "mission":{"launch_latitude_deg":"28.5","launch_longitude_deg":"0","target_altitude_km":"200","target_inclination_deg":"51.6","payload_mass_t":"12","duration_s":"900"},
      "formats":fs,"range_proof":{"widened_products":widened,"maximum_required_bits_including_sign":max(x["required_bits_including_sign"] for x in widened),"explicit_two_word_intermediate_required":True},
      "limits":{"maximum_stages":4,"bending_modes_per_transverse_axis":1,"slosh_modes_per_transverse_axis":1,"maximum_distributions":24,"maximum_angle_of_attack_deg":"15"},
      "frozen_planar":{"truth_checksum":"0xc86045a0","sensor_checksum":"0x47d11fb0","navigation_checksum":"0xc6f9da7b","flight_checksum":"0x02ce28ef","kst3_crc32":"0xaf79b36e","phase2_compatibility":"0xcc57612b"},
      "source_sha256":hashlib.sha256((json.dumps(source,sort_keys=True,separators=(",",":"))+"\n").encode()).hexdigest()
    }

def rust(c):
    m=c["mission"]
    return "\n".join([
      "// Generated by phase5/reference/generate_contract.py.","// Do not edit by hand.","",
      f'pub const PHASE5_NUMERIC_CONTRACT: &str = "{CONTRACT}";',f"pub const PHASE5_NUMERIC_CONTRACT_ID: u32 = {c['contract_id']};",
      f"pub const PHASE5_ENVIRONMENT_ID: u32 = {c['environment_id']};",f"pub const PHASE5_SCENARIO_ID: u32 = {c['scenario_id']};",
      f"pub const PHASE5_BASE_KSC2_CRC32: u32 = {BASE_KSC2_CRC};","pub const PHASE5_MISSION_STEP_Q16: i32 = 8192;","pub const PHASE5_FAST_STEP_Q16: i32 = 2048;","pub const PHASE5_ATTITUDE_SUBSTEPS: u8 = 4;","pub const PHASE5_MISSION_STEPS: u32 = 7200;",
      f"pub const PHASE5_LAUNCH_LATITUDE_TURN32: u32 = {turn32(m['launch_latitude_deg'])};",f"pub const PHASE5_TARGET_INCLINATION_TURN32: u32 = {turn32(m['target_inclination_deg'])};",
      f"pub const PHASE5_TARGET_RADIUS_Q12: i32 = {raw(str(6378.137+float(m['target_altitude_km'])),12)};",f"pub const PHASE5_PAYLOAD_MASS_Q12: i32 = {raw(m['payload_mass_t'],12)};","pub const PHASE5_RCS_PROPELLANT_Q12: i32 = 410;","pub const PHASE5_MAX_AOA_TURN16: u16 = 2731;","pub const PHASE5_CAMPAIGN_SEED: u32 = 0x4b534135;","pub const PHASE5_ROUTINE_RUNS: u16 = 32;","pub const PHASE5_REFERENCE_RUNS: u16 = 256;","",
      "pub const PHASE5_PLANAR_TRUTH_CHECKSUM: u32 = 0xc86045a0;","pub const PHASE5_PLANAR_SENSOR_CHECKSUM: u32 = 0x47d11fb0;","pub const PHASE5_PLANAR_NAV_CHECKSUM: u32 = 0xc6f9da7b;","pub const PHASE5_PLANAR_FLIGHT_CHECKSUM: u32 = 0x02ce28ef;","pub const PHASE5_PLANAR_KST3_CRC32: u32 = 0xaf79b36e;","pub const PHASE5_PLANAR_PHASE2_CHECKSUM: u32 = 0xcc57612b;",""
    ])

def outputs(root:Path):
    source=json.loads((root/"phase5/examples/ksa5a-200km-51.6.json").read_text())
    assert source["base_ksc2_crc32"]=="0x5d362512" and source["payload_mass_t"]=="12" and source["attitude_substeps"]==4
    c=contract(source)
    result={root/"phase5/contract-v1.json":(json.dumps(c,indent=2)+"\n").encode(),root/"phase5/generated/contract_v1.rs":rust(c).encode()}
    for p,data in list(result.items()): result[p.with_name(p.name+".sha256")]=(hashlib.sha256(data).hexdigest()+"  "+p.name+"\n").encode()
    for p in [root/"phase5/examples/ksa5a-200km-51.6.json",root/"phase5/scenario-v5.schema.json"]:
        data=p.read_bytes(); result[p.with_name(p.name+".sha256")]=(hashlib.sha256(data).hexdigest()+"  "+p.name+"\n").encode()
    return result

def main():
    ap=argparse.ArgumentParser(); ap.add_argument("--check",action="store_true"); args=ap.parse_args(); root=Path(__file__).resolve().parents[2]; failed=False
    for p,data in outputs(root).items():
        if args.check:
            if not p.exists() or p.read_bytes()!=data: print("stale or missing:",p.relative_to(root),file=sys.stderr); failed=True
        else: p.parent.mkdir(parents=True,exist_ok=True); p.write_bytes(data); print(p.relative_to(root))
    return int(failed)
if __name__=="__main__": raise SystemExit(main())
