#!/usr/bin/env python3
"""Independent exact integer vectors for Phase 5 bending and slosh modes."""
from __future__ import annotations

import argparse
import hashlib
import json
import math
from decimal import Decimal, ROUND_HALF_UP
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
JSON_OUT = ROOT / "phase5" / "generated" / "flexible-vectors-v1.json"
RUST_OUT = ROOT / "phase5" / "generated" / "flexible_vectors_v1.rs"
DT = 1 << 11


def fixed(value: str | float, bits: int) -> int:
    return int((Decimal(str(value)) * (1 << bits)).to_integral_value(rounding=ROUND_HALF_UP))


def ratio(n: int, d: int) -> int:
    q, r = divmod(n, d)
    return q + (1 if r * 2 >= d else 0)


def mul(a: int, b: int, shift: int) -> int:
    value = ratio(abs(a) * abs(b), 1 << shift)
    return -value if (a < 0) ^ (b < 0) else value


def step_mode(state: list[int], params: list[int], drive: int) -> list[int]:
    omega, damping, gain = params
    omega2 = mul(omega, omega, 16)
    damping_coefficient = mul(damping, omega, 15)
    acceleration = mul(gain, drive, 16) - mul(omega2, state[0], 16) - mul(damping_coefficient, state[1], 16)
    rate = state[1] + mul(acceleration, DT, 16)
    displacement = state[0] + mul(rate, DT, 16)
    return [displacement, rate]


def step(state: list[int], bend: list[int], slosh: list[int], drive: list[int]) -> list[int]:
    return (
        step_mode(state[0:2], bend, drive[0])
        + step_mode(state[2:4], slosh, drive[2])
        + step_mode(state[4:6], bend, drive[1])
        + step_mode(state[6:8], slosh, drive[3])
    )


def repeated(state: list[int], bend: list[int], slosh: list[int], drive: list[int], count: int) -> list[int]:
    for _ in range(count):
        state = step(state, bend, slosh, drive)
    return state


def build() -> dict:
    bend = [fixed(2 * math.pi * 1.2, 16), fixed("0.015", 16), fixed("0.10", 16)]
    bend_undamped = [bend[0], 0, bend[2]]
    slosh = [fixed(2 * math.pi * 0.45, 16), fixed("0.03", 16), fixed("0.50", 16)]
    initial = [
        fixed("0.01", 24), 0,
        fixed("0.10", 24), 0,
        fixed("-0.005", 24), 0,
        fixed("-0.05", 24), 0,
    ]
    drive = [fixed("0.2", 24), fixed("-0.1", 24), fixed("0.03", 24), fixed("0.02", 24)]
    zero = [0, 0, 0, 0]
    symmetric = [fixed("0.1", 24)] * 4
    return {
        "contract": "ksa64.flexible-vectors.phase5-v1",
        "dt_q16": DT,
        "bending_parameters_q16": bend,
        "bending_undamped_q16": bend_undamped,
        "slosh_parameters_q16": slosh,
        "initial_q24": initial,
        "drive_q24": drive,
        "one_step_q24": step(initial, bend, slosh, drive),
        "damped_zero_drive_128_q24": repeated(initial.copy(), bend, slosh, zero, 128),
        "undamped_zero_drive_128_q24": repeated(initial.copy(), bend_undamped, slosh, zero, 128),
        "driven_128_q24": repeated(initial.copy(), bend, slosh, drive, 128),
        "symmetric_drive_q24": symmetric,
        "symmetric_64_q24": repeated([0] * 8, bend, slosh, symmetric, 64),
    }


def rust(d: dict) -> str:
    def arr(values: list[int]) -> str:
        return "[" + ", ".join(str(v) for v in values) + "]"
    return f"""// Generated by phase5/reference/generate_flexible_vectors.py.
// Do not edit by hand.

pub const DT_Q16: i32 = {d['dt_q16']};
pub const BENDING_PARAMETERS_Q16: [i32; 3] = {arr(d['bending_parameters_q16'])};
pub const BENDING_UNDAMPED_Q16: [i32; 3] = {arr(d['bending_undamped_q16'])};
pub const SLOSH_PARAMETERS_Q16: [i32; 3] = {arr(d['slosh_parameters_q16'])};
pub const INITIAL_Q24: [i32; 8] = {arr(d['initial_q24'])};
pub const DRIVE_Q24: [i32; 4] = {arr(d['drive_q24'])};
pub const ONE_STEP_Q24: [i32; 8] = {arr(d['one_step_q24'])};
pub const DAMPED_ZERO_DRIVE_128_Q24: [i32; 8] = {arr(d['damped_zero_drive_128_q24'])};
pub const UNDAMPED_ZERO_DRIVE_128_Q24: [i32; 8] = {arr(d['undamped_zero_drive_128_q24'])};
pub const DRIVEN_128_Q24: [i32; 8] = {arr(d['driven_128_q24'])};
pub const SYMMETRIC_DRIVE_Q24: [i32; 4] = {arr(d['symmetric_drive_q24'])};
pub const SYMMETRIC_64_Q24: [i32; 8] = {arr(d['symmetric_64_q24'])};
"""


def write_or_check(path: Path, data: bytes, check: bool) -> None:
    if check:
        if not path.exists() or path.read_bytes() != data:
            raise SystemExit(f"stale generated artifact: {path.relative_to(ROOT)}")
        return
    path.write_bytes(data)
    digest = hashlib.sha256(data).hexdigest()
    path.with_suffix(path.suffix + ".sha256").write_text(f"{digest}  {path.name}\n", encoding="ascii")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    data = build()
    write_or_check(JSON_OUT, (json.dumps(data, indent=2) + "\n").encode(), args.check)
    write_or_check(RUST_OUT, rust(data).encode(), args.check)


if __name__ == "__main__":
    main()