#!/usr/bin/env python3
"""Independent exact-integer and float64 references for Phase 5 rigid body work."""
from __future__ import annotations

import argparse
import hashlib
import json
import math
from decimal import Decimal, ROUND_HALF_UP
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
JSON_OUT = ROOT / "phase5" / "generated" / "rigid-body-vectors-v1.json"
RUST_OUT = ROOT / "phase5" / "generated" / "rigid_body_vectors_v1.rs"
ONE = 1 << 30
DT = 1 << 11


def fixed(text: str, bits: int) -> int:
    return int((Decimal(text) * (1 << bits)).to_integral_value(rounding=ROUND_HALF_UP))


def rounded_ratio(n: int, d: int) -> int:
    q, r = divmod(n, d)
    return q + (1 if r * 2 >= d else 0)


def mul(a: int, b: int, shift: int) -> int:
    value = rounded_ratio(abs(a) * abs(b), 1 << shift)
    return -value if (a < 0) ^ (b < 0) else value


def div_scaled(a: int, b: int, shift: int) -> int:
    value = rounded_ratio(abs(a) << shift, abs(b))
    return -value if (a < 0) ^ (b < 0) else value


def normalize(q: list[int]) -> list[int]:
    norm_sq = sum(mul(v, v, 30) for v in q)
    norm = math.isqrt(norm_sq << 30)
    return [div_scaled(v, norm, 30) for v in q]


def acceleration(inertia: list[int], rate: list[int], torque: list[int]) -> list[int]:
    products = [mul(rate[1], rate[2], 24), mul(rate[2], rate[0], 24), mul(rate[0], rate[1], 24)]
    differences = [inertia[2] - inertia[1], inertia[0] - inertia[2], inertia[1] - inertia[0]]
    coupling = [mul(differences[i], products[i], 20) for i in range(3)]
    return [div_scaled(torque[i] * 1000 - coupling[i], inertia[i], 20) for i in range(3)]


def integrate_attitude(q: list[int], rate: list[int]) -> list[int]:
    w, x, y, z = q
    wx, wy, wz = rate
    derivative = [
        -mul(x, wx, 30) - mul(y, wy, 30) - mul(z, wz, 30),
        mul(w, wx, 30) + mul(y, wz, 30) - mul(z, wy, 30),
        mul(w, wy, 30) + mul(z, wx, 30) - mul(x, wz, 30),
        mul(w, wz, 30) + mul(x, wy, 30) - mul(y, wx, 30),
    ]
    return normalize([q[i] + mul(derivative[i], DT, 11) for i in range(4)])


def step(state: dict, inertia: list[int], torque: list[int]) -> tuple[dict, list[int]]:
    alpha = acceleration(inertia, state["rate"], torque)
    rate = [state["rate"][i] + mul(alpha[i], DT, 16) for i in range(3)]
    attitude = integrate_attitude(state["attitude"], rate)
    return {"attitude": attitude, "rate": rate}, alpha


def repeated(state: dict, inertia: list[int], torque: list[int], count: int) -> dict:
    for _ in range(count):
        state, _ = step(state, inertia, torque)
    return state


def build() -> dict:
    spherical = [1000 << 12] * 3
    asymmetric = [1000 << 12, 1200 << 12, 1500 << 12]
    torque_x = [fixed("0.5", 16), 0, 0]
    rest = {"attitude": [ONE, 0, 0, 0], "rate": [0, 0, 0]}
    asymmetric_state = {
        "attitude": [ONE, 0, 0, 0],
        "rate": [fixed("0.1", 24), fixed("0.2", 24), fixed("-0.15", 24)],
    }
    constant_rate_state = {
        "attitude": [ONE, 0, 0, 0],
        "rate": [0, 0, fixed("0.25", 24)],
    }
    spherical_step, spherical_alpha = step(rest, spherical, torque_x)
    asymmetric_step, asymmetric_alpha = step(asymmetric_state, asymmetric, [0, 0, 0])
    return {
        "contract": "ksa64.rigid-body-vectors.phase5-v1",
        "dt_q16": DT,
        "spherical_inertia_q12": spherical,
        "asymmetric_inertia_q12": asymmetric,
        "torque_x_q16": torque_x,
        "asymmetric_initial": asymmetric_state,
        "spherical_one_step": spherical_step,
        "spherical_alpha_q24": spherical_alpha,
        "asymmetric_one_step": asymmetric_step,
        "asymmetric_alpha_q24": asymmetric_alpha,
        "constant_torque_64": repeated(rest.copy(), spherical, torque_x, 64),
        "constant_rate_64": repeated(constant_rate_state, spherical, [0, 0, 0], 64),
        "float64": {
            "constant_torque_final_rate_x": 1.0,
            "constant_torque_final_angle_x": 1.0,
            "constant_rate_final_angle_z": 0.5,
        },
    }


def rust(data: dict) -> str:
    def arr(v: list[int]) -> str:
        return "[" + ", ".join(str(x) for x in v) + "]"
    def state(prefix: str, value: dict) -> str:
        return f"pub const {prefix}_ATTITUDE_Q30: [i32; 4] = {arr(value['attitude'])};\npub const {prefix}_RATE_Q24: [i32; 3] = {arr(value['rate'])};\n"
    return f"""// Generated by phase5/reference/generate_rigid_body_vectors.py.
// Do not edit by hand.

pub const DT_Q16: i32 = {data['dt_q16']};
pub const SPHERICAL_INERTIA_Q12: [i32; 3] = {arr(data['spherical_inertia_q12'])};
pub const ASYMMETRIC_INERTIA_Q12: [i32; 3] = {arr(data['asymmetric_inertia_q12'])};
pub const TORQUE_X_Q16: [i32; 3] = {arr(data['torque_x_q16'])};
{state('ASYMMETRIC_INITIAL', data['asymmetric_initial'])}{state('SPHERICAL_ONE_STEP', data['spherical_one_step'])}pub const SPHERICAL_ALPHA_Q24: [i32; 3] = {arr(data['spherical_alpha_q24'])};
{state('ASYMMETRIC_ONE_STEP', data['asymmetric_one_step'])}pub const ASYMMETRIC_ALPHA_Q24: [i32; 3] = {arr(data['asymmetric_alpha_q24'])};
{state('CONSTANT_TORQUE_64', data['constant_torque_64'])}{state('CONSTANT_RATE_64', data['constant_rate_64'])}"""


def write_or_check(path: Path, payload: bytes, check: bool) -> None:
    if check:
        if not path.exists() or path.read_bytes() != payload:
            raise SystemExit(f"stale generated artifact: {path.relative_to(ROOT)}")
        return
    path.write_bytes(payload)
    digest = hashlib.sha256(payload).hexdigest()
    path.with_suffix(path.suffix + ".sha256").write_text(f"{digest}  {path.name}\n", encoding="ascii")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    data = build()
    write_or_check(JSON_OUT, (json.dumps(data, indent=2) + "\n").encode(), args.check)
    write_or_check(RUST_OUT, rust(data).encode(), args.check)


if __name__ == "__main__":
    main()