#!/usr/bin/env python3
"""Generate independent integer reference vectors for Phase 5 spatial math."""
from __future__ import annotations

import argparse
import hashlib
import json
import math
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
JSON_OUT = ROOT / "phase5" / "generated" / "spatial-vectors-v1.json"
RUST_OUT = ROOT / "phase5" / "generated" / "spatial_vectors_v1.rs"
ONE = 1 << 30


def rounded_ratio(numerator: int, denominator: int) -> int:
    quotient, remainder = divmod(numerator, denominator)
    return quotient + (1 if remainder * 2 >= denominator else 0)


def mul(a: int, b: int, shift: int) -> int:
    negative = (a < 0) ^ (b < 0)
    value = rounded_ratio(abs(a) * abs(b), 1 << shift)
    return -value if negative else value


def div_scaled(a: int, b: int, shift: int) -> int:
    negative = (a < 0) ^ (b < 0)
    value = rounded_ratio(abs(a) << shift, abs(b))
    return -value if negative else value


def cross(a: list[int], b: list[int], shift: int) -> list[int]:
    return [
        mul(a[1], b[2], shift) - mul(a[2], b[1], shift),
        mul(a[2], b[0], shift) - mul(a[0], b[2], shift),
        mul(a[0], b[1], shift) - mul(a[1], b[0], shift),
    ]


def hamilton(a: list[int], b: list[int]) -> list[int]:
    aw, ax, ay, az = a
    bw, bx, by, bz = b
    return [
        mul(aw, bw, 30) - mul(ax, bx, 30) - mul(ay, by, 30) - mul(az, bz, 30),
        mul(aw, bx, 30) + mul(ax, bw, 30) + mul(ay, bz, 30) - mul(az, by, 30),
        mul(aw, by, 30) + mul(ay, bw, 30) + mul(az, bx, 30) - mul(ax, bz, 30),
        mul(aw, bz, 30) + mul(az, bw, 30) + mul(ax, by, 30) - mul(ay, bx, 30),
    ]


def normalize(q: list[int]) -> list[int]:
    norm_sq = sum(mul(value, value, 30) for value in q)
    norm = math.isqrt(norm_sq << 30)
    return [div_scaled(value, norm, 30) for value in q]


def rotate(q: list[int], vector: list[int]) -> list[int]:
    qv = q[1:]
    first = cross(qv, vector, 30)
    twice = [value * 2 for value in first]
    scalar = [mul(value, q[0], 30) for value in twice]
    second = cross(qv, twice, 30)
    return [vector[i] + scalar[i] + second[i] for i in range(3)]


def build() -> dict:
    scale = 1 << 16
    a = [5 * scale // 4, -5 * scale // 2, 3 * scale // 4]
    b = [-scale // 2, 4 * scale, 2 * scale]
    root_half = round(math.sqrt(0.5) * ONE)
    qz90 = [root_half, 0, 0, root_half]
    qx90 = [root_half, root_half, 0, 0]
    unnormalized = [ONE, ONE // 10, -(ONE // 20), ONE // 40]
    return {
        "contract": "ksa64.spatial-vectors.phase5-v1",
        "vector_fractional_bits": 16,
        "a": a,
        "b": b,
        "dot_q16": sum(mul(a[i], b[i], 16) for i in range(3)),
        "cross_q16": cross(a, b, 16),
        "qz90_q30": qz90,
        "qx90_q30": qx90,
        "hamilton_q30": hamilton(qz90, qx90),
        "rotated_x_q16": rotate(qz90, [scale, 0, 0]),
        "unnormalized_q30": unnormalized,
        "normalized_q30": normalize(unnormalized),
    }


def rust(data: dict) -> str:
    def arr(values: list[int]) -> str:
        return "[" + ", ".join(str(value) for value in values) + "]"
    return f"""// Generated by phase5/reference/generate_spatial_vectors.py.
// Do not edit by hand.

pub const VECTOR_A_Q16: [i32; 3] = {arr(data['a'])};
pub const VECTOR_B_Q16: [i32; 3] = {arr(data['b'])};
pub const DOT_Q16: i32 = {data['dot_q16']};
pub const CROSS_Q16: [i32; 3] = {arr(data['cross_q16'])};
pub const QZ90_Q30: [i32; 4] = {arr(data['qz90_q30'])};
pub const QX90_Q30: [i32; 4] = {arr(data['qx90_q30'])};
pub const HAMILTON_Q30: [i32; 4] = {arr(data['hamilton_q30'])};
pub const ROTATED_X_Q16: [i32; 3] = {arr(data['rotated_x_q16'])};
pub const UNNORMALIZED_Q30: [i32; 4] = {arr(data['unnormalized_q30'])};
pub const NORMALIZED_Q30: [i32; 4] = {arr(data['normalized_q30'])};
"""


def write_or_check(path: Path, payload: bytes, check: bool) -> None:
    if check:
        if not path.exists() or path.read_bytes() != payload:
            raise SystemExit(f"stale generated artifact: {path.relative_to(ROOT)}")
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(payload)
    digest = hashlib.sha256(payload).hexdigest()
    path.with_suffix(path.suffix + ".sha256").write_text(
        f"{digest}  {path.name}\n", encoding="ascii"
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    data = build()
    write_or_check(JSON_OUT, (json.dumps(data, indent=2) + "\n").encode(), args.check)
    write_or_check(RUST_OUT, rust(data).encode(), args.check)


if __name__ == "__main__":
    main()